### ISSUE TITLE
小雅集成版打不开502 bad gateway

### ISSUE THREAD

**Issue by kuhayashi** [power721/alist-tvbox#108]
N1盒子openwrt安装小雅集成版，全部默认配置。

小雅5344端口页面打不开，显示502 bad gateway
此时Log里面错误：
WARN 87 --- [   scheduling-1] c.h.a.service.AListLocalService          : I/O error on GET request for "http://localhost:5244/api/public/settings": Failed to connect to localhost/127.0.0.1:5244

如果在4567端口管理页面点vod的话也会弹出错误：
I/O error on POST request for "http://localhost:5244/api/fs/list": Failed to connect to localhost/127.0.0.1:5244
此时Log 错误：
ERROR 87 --- [nio-4567-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:5244/api/fs/list": Failed to connect to localhost/127.0.0.1:5244] with root cause

java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[na:na]
        等等后面一长串

请问有什么解决办法吗？谢谢！

**Comment by Wenlong-Guo** [comment]
没配置帐号就502 配上帐号就看到了

**Comment by kuhayashi** [comment]
> 没配置帐号就502 配上帐号就看到了

万分感谢！！解决了！

**Comment by Wenlong-Guo** [comment]
> > 没配置帐号就502 配上帐号就看到了
> 
> 万分感谢！！解决了！

我也是误打误撞,issue可以关闭了

**Comment by leniou** [comment]
我有设置帐号也不行。 前几天还可以正常用的。昨天突然出现的错误
