### ISSUE TITLE
使用xiaoya_tvbox套娃alist（序列2），已经构建套娃的索引，VOD点播模式搜索不显示第二站点套娃alist内容，网盘模式VOD1可以搜索到套娃内容

### ISSUE THREAD

**Issue by lonelyice521** [power721/alist-tvbox#118]
您好，使用xiaoya_tvbox套娃alist（第二个站点），已经构建套娃的索引，VOD点播模式搜索不显示第二站点套娃alist内容，网盘模式VOD1可以搜索到套娃内容。 请问下这个点播模式的搜索就这样设计（仅能搜索第一个站点的内容）的还是 我配置的有问题？
请帮忙解答下，谢谢。

**Comment by power721** [comment]
需要自己刮削才能搜索

**Comment by intelsong** [comment]
> 需要自己刮削才能搜索

我也想知道这个括捎功能在哪里？
