### ISSUE TITLE
failed get objs: failed to list objs: driver not init

### ISSUE THREAD

**Issue by hyy34** [power721/alist-tvbox#123]
5344的xiaoya 集成版提示这个，是有什么设置没做吗？

**Comment by power721** [comment]
重启

**Comment by death4444** [comment]
我来补一发手把手教程：
首先检查问题：
![Screenshot_2024-10-07-15-39-05-148_org telegram messengers](https://github.com/user-attachments/assets/a21a4c0c-d3e3-48db-af27-19b9d3b3aca5)
发现问题，token获取的通道不对，这个报错说明我选择了APP通道，但是获取的是alist的token：
![image](https://github.com/user-attachments/assets/dcd3e3d4-b3d3-413a-b4aa-cc020180a184)
改正设置：
![小雅报错failed get objs failed to list objs driver not init](https://github.com/user-attachments/assets/cf11ccf0-bbb1-4cd2-9969-2fc0da330cb3)
点击更新
重启服务
![image](https://github.com/user-attachments/assets/036ca8dd-c1da-46da-a608-2156bafd3375)
