### ISSUE TITLE
大佬，能否把缓存清理做成可自定义清理的方式

### ISSUE THREAD

**Issue by chris6868** [power721/alist-tvbox#124]
大佬由于阿里最近的严打，可否把清理缓存做成可以自定义的方式，比如按时间间隔，按次数等，具体方式由大佬定夺，还有就是vod的很多资源都是过期的资源，可否新增一个一键删除一键重新生成，感谢大佬

**Comment by specteryong** [comment]
您好，您的邮件已收到，谢谢！
