### ISSUE TITLE
希望支持arm-v7

### ISSUE THREAD

**Issue by 275080225** [power721/alist-tvbox#13]
pi@raspberrypi:~ $ sudo bash -c "$(curl -fsSL https://d.har01d.cn/update_xiaoya.sh)" /etc/xiaoya 4567 5344
使用配置目录： 4567
端口映射： 5344:4567  5344:80
默认端口变更为4567

Total reclaimed space: 0B
下载最新Docker镜像，平台：linux/arm/v7
Error response from daemon: manifest for haroldli/xiaoya-tvbox:arm-v7 not found: manifest unknown: manifest unknown

**Comment by power721** [comment]
编了一个arm v7的包，你自己测试一下。

**Comment by power721** [comment]
一键安装脚本，不需要后面的参数，你写错了。
sudo bash -c "$(curl -fsSL https://d.har01d.cn/update_xiaoya.sh)"

**Comment by 275080225** [comment]
4567  5344都打不开
查看日志发现：
'data.zip' saved
193.0741
/entrypoint.sh: line 38: java: not found
replace token? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'

**Comment by power721** [comment]
我没有设备测试，你再试试

**Comment by power721** [comment]
还是不行，我在改改

**Comment by 275080225** [comment]
刚试了，日志：
docker logs -f xiaoya-tvbox
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip              5% |*                               | 13885  0:00:16 ETA
tvbox.zip            100% |********************************|  232k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'update.zip'
update.zip           100% |********************************|  104k  0:00:00 ETA
'update.zip' saved
Wed Jul 12 20:56:10 CST 2023 total 226 records
v3.4.0
Runtime error near line 3003: UNIQUE constraint failed: x_storages.mount_path (19)
Wed Jul 12 20:56:11 CST 2023 update database successfully
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'index.zip'
index.zip              3% |*                               |  153k  0:00:29 ETA
index.zip             80% |*************************       | 3789k  0:00:00 ETA
index.zip            100% |********************************| 4692k  0:00:00 ETA
'index.zip' saved
Wed Jul 12 20:56:14 CST 2023 update index succesfully, your new version.txt is 0.5.89
local data version: 0.0, remote data version: 193.1903
download data.zip
Connecting to d.har01d.cn (1.117.140.221:80)
saving to 'data.zip'
data.zip               0% |                                | 49420  0:02:15 ETA
data.zip               2% |                                |  177k  0:01:12 ETA
data.zip               7% |**                              |  525k  0:00:34 ETA
data.zip              16% |*****                           | 1082k  0:00:20 ETA
data.zip              25% |********                        | 1698k  0:00:14 ETA
data.zip              34% |***********                     | 2301k  0:00:11 ETA
data.zip              43% |**************                  | 2886k  0:00:08 ETA
data.zip              52% |****************                | 3473k  0:00:07 ETA
data.zip              61% |*******************             | 4052k  0:00:05 ETA
data.zip              70% |**********************          | 4611k  0:00:04 ETA
data.zip              79% |*************************       | 5213k  0:00:02 ETA
data.zip              87% |****************************    | 5773k  0:00:01 ETA
data.zip              96% |******************************  | 6365k  0:00:00 ETA
data.zip             100% |********************************| 6585k  0:00:00 ETA
'data.zip' saved
193.1903
/entrypoint.sh: line 46: java: not found
replace token? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip            100% |********************************|  232k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'update.zip'
update.zip            39% |************                    | 42445  0:00:01 ETA
update.zip           100% |********************************|  104k  0:00:00 ETA
'update.zip' saved
Wed Jul 12 20:56:45 CST 2023 total 226 records

**Comment by power721** [comment]
这个应用消耗内存多，armv7内存设备估计也不够。

**Comment by 275080225** [comment]
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip             86% |***************************     |  201k  0:00:00 ETA
tvbox.zip            100% |********************************|  232k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'update.zip'
update.zip            42% |*************                   | 45301  0:00:01 ETA
update.zip           100% |********************************|  104k  0:00:00 ETA
'update.zip' saved
Wed Jul 12 21:47:16 CST 2023 total 226 records
v3.4.0
Runtime error near line 3003: UNIQUE constraint failed: x_storages.mount_path (19)
Wed Jul 12 21:47:16 CST 2023 update database successfully
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'index.zip'
index.zip              0% |                                | 13883  0:05:46 ETA
index.zip              6% |**                              |  323k  0:00:27 ETA
index.zip            100% |********************************| 4692k  0:00:00 ETA
'index.zip' saved
Wed Jul 12 21:47:20 CST 2023 update index succesfully, your new version.txt is 0.5.89
local data version: 193.1903, remote data version: 193.1903
Segmentation fault (core dumped)
replace token? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip              8% |**                              | 19597  0:00:11 ETA
tvbox.zip            100% |********************************|  232k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'update.zip'
update.zip            20% |******                          | 22453  0:00:03 ETA
update.zip           100% |********************************|  104k  0:00:00 ETA
'update.zip' saved
Wed Jul 12 21:47:26 CST 2023 total 226 records
v3.4.0
Runtime error near line 3003: UNIQUE constraint failed: x_storages.mount_path (19)
Wed Jul 12 21:47:26 CST 2023 update database successfully
Wed Jul 12 21:47:26 CST 2023 current index file version is updated, no need to upgrade
local data version: 193.1903, remote data version: 193.1903
Segmentation fault (core dumped)
replace token? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip              5% |*                               | 13885  0:00:16 ETA
tvbox.zip            100% |********************************|  232k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'update.zip'
update.zip            12% |****                            | 13885  0:00:06 ETA
update.zip           100% |********************************|  104k  0:00:00 ETA
'update.zip' saved
Wed Jul 12 21:47:32 CST 2023 total 226 records
v3.4.0
Runtime error near line 3003: UNIQUE constraint failed: x_storages.mount_path (19)
Wed Jul 12 21:47:32 CST 2023 update database successfully
Wed Jul 12 21:47:32 CST 2023 current index file version is updated, no need to upgrade
local data version: 193.1903, remote data version: 193.1903
Segmentation fault (core dumped)
replace token? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip             38% |************                    | 90997  0:00:01 ETA
tvbox.zip            100% |********************************|  232k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'update.zip'
update.zip            82% |**************************      | 88141  0:00:00 ETA
update.zip           100% |********************************|  104k  0:00:00 ETA
'update.zip' saved
Wed Jul 12 21:47:38 CST 2023 total 226 records

**Comment by power721** [comment]
又编了一个包，你试试

**Comment by 275080225** [comment]
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip              5% |*                               | 13885  0:00:16 ETA
tvbox.zip            100% |********************************|  232k  0:00:00 ETA
'tvbox.zip' saved
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'update.zip'
update.zip            26% |********                        | 28165  0:00:02 ETA
update.zip           100% |********************************|  104k  0:00:00 ETA
'update.zip' saved
Thu Jul 13 16:19:03 CST 2023 total 226 records
v3.4.0
Runtime error near line 3003: UNIQUE constraint failed: x_storages.mount_path (19)
Thu Jul 13 16:19:03 CST 2023 update database successfully
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'index.zip'
index.zip              0% |                                | 13883  0:05:46 ETA
index.zip             10% |***                             |  490k  0:00:17 ETA
index.zip            100% |********************************| 4692k  0:00:00 ETA
'index.zip' saved
Thu Jul 13 16:19:08 CST 2023 update index succesfully, your new version.txt is 0.5.89
local data version: 193.1903, remote data version: 194.1422
download data.zip
Connecting to d.har01d.cn (1.117.140.221:80)
saving to 'data.zip'
data.zip               1% |                                |  122k  0:00:52 ETA
data.zip              16% |*****                           | 1119k  0:00:09 ETA
data.zip              25% |********                        | 1712k  0:00:08 ETA
data.zip              35% |***********                     | 2330k  0:00:07 ETA
data.zip              43% |*************                   | 2870k  0:00:06 ETA
data.zip              52% |****************                | 3463k  0:00:05 ETA
data.zip              60% |*******************             | 4018k  0:00:04 ETA
data.zip              69% |**********************          | 4564k  0:00:03 ETA
data.zip              77% |************************        | 5092k  0:00:02 ETA
data.zip              86% |***************************     | 5685k  0:00:01 ETA
data.zip              95% |******************************  | 6289k  0:00:00 ETA
data.zip             100% |********************************| 6587k  0:00:00 ETA
'data.zip' saved
194.1422
Segmentation fault (core dumped)
replace token? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Connecting to docker.xiaoya.pro (152.70.149.62:80)
saving to 'tvbox.zip'
tvbox.zip             35% |***********                     | 85285  0:00:01 ETA

**Comment by power721** [comment]
没法了，试了好的Java都不行

**Comment by 1714801500** [comment]
我的是树莓派2B，没有arm v7的版本镜像。。
