### ISSUE TITLE
重启docker容器后，电影数据列表重置问题

### ISSUE THREAD

**Issue by amber6hua** [power721/alist-tvbox#135]
应用版本：351.1715

安装版本
sudo bash -c "$(curl -fsSL https://d.har01d.cn/update_xiaoya.sh)"

初次安装时，电影数据列表是最新的（本地版本：353.1917）

重启docker后，电影数据列表回到了上个版本（失去了353.1917的数据）

往列表里添加的新数据，也会重置。（新添加的数据id从500001开始，和初始数据重复）

新老环境都是这样的问题

**Comment by 775728212** [comment]
这个数据库好像是不持久化的 每次重启都会跑一遍初始化脚本  我也不太懂JAVA

**Comment by amber6hua** [comment]
java我也是半懂不懂的，正常不应该执行每次重启都初始化数据库的，最多执行增量更新，感觉是比较数据版本号那里出问题

**Comment by 775728212** [comment]
> java我也是半懂不懂的，正常不应该执行每次重启都初始化数据库的，最多执行增量更新，感觉是比较数据版本号那里出问题

哈哈 你快给改改 顺便吧失效的资源自动删除了

**Comment by amber6hua** [comment]
这就很尴尬了
半懂：勉强看得懂
不懂：完全改不来

**Comment by 775728212** [comment]
> 这就很尴尬了 半懂：勉强看得懂 不懂：完全改不来

一样 勉强看得懂 写 就完全不行了

**Comment by power721** [comment]
修复
