### ISSUE TITLE
希望优化一下外网访问

### ISSUE THREAD

**Issue by WudaxStudio** [power721/alist-tvbox#149]
目前power大佬的系统里，在高级设置里面，可以打开“订阅域名支持https访问”，这样映射到外网后，可以通过域名和端口访问到订阅地址，但是有以下几个问题：
1、内网访问时，地址直接变成https了，这样导致内网下的TVBOX服务无法正常使用；
![image](https://github.com/power721/alist-tvbox/assets/130849175/8cfd16a4-5132-47c0-bb93-acc4975a829e)
2、如果不配置https，外网配置了https访问，如图所示，那内部还是保持了用http方式，导致无法正常使用，必须要通过强制使用302跳转，会非常麻烦。
![image](https://github.com/power721/alist-tvbox/assets/130849175/2792a692-5539-44cf-b648-ebd09630077f)
以上，希望power大佬能够优化
（如直接沿用服务端的方式，服务端获取的scheme如果是http那配置页也是，与主服务端保持一致）
以上，谢谢大佬支持！

**Comment by power721** [comment]
fixed
