### ISSUE TITLE
请问是否支持使用自己的api？

### ISSUE THREAD

**Issue by outcastveron** [power721/alist-tvbox#152]
xiaoya 可以添加open_api.txt 使用自己api，本项目是否支持？是直接在etc/xiaoya 增加相关文件还是在data/ 路径下操作？主账号和挂载账号是否都需要更新token？

附xiaoya 使用自己api的方法供参考

用open_api解除了限速，能正常看4k了，为了让之后的朋友少走弯路，简单总结一下
1、在 
https://www.aliyundrive.com/developer/f   
申请开发者权限，理由自己想办法编，我让gpt帮忙编的。
2、得到授权后在 
https://www.aliyundrive.com/developer/f
 新建一个app，三个权限都要同意（我就在这步卡了半天）。授权回调uri填

https://alist.nn.ci/tool/aliyundrive/request.html

https://openapi.alipan.com/oauth/access_token
3、获取自己的app id和App Secret后在open_api.txt中按这个格式填
https://openapi.alipan.com/oauth/access_token（空格）app id（空格）AppSecret
4、在
https://alist.nn.ci/tool/aliyundrive/request.html   中选  use my own client，输入自己的app id和App Secret，重新获取自己的opentoken，替换进myopentoken.txt中。
5、重启小雅docker

**Comment by power721** [comment]
更新试试

**Comment by power721** [comment]
获取自己的app id和App Secret后在配置-》高级设置填写

**Comment by outcastveron** [comment]
主账号和挂载账号是否都需要更新refresh token？已经更新并且填写，一直报错

INFO [2024-01-07 15:23:27] Open API Client ID:
INFO [2024-01-07 15:23:27] refreshOpenToken 33 https://api-cf.nn.ci/alist/ali_open/token false
ERRO [2024-01-07 15:23:28] refreshOpenToken error: failed to refresh open token: invalid client_id

可能操作太频繁了

**Comment by power721** [comment]
client_id是空的。url也没有替换。
看起来没有保存成功。重新配置再重启试试。

**Comment by outcastveron** [comment]
已经成功使用个人api加载。
发现新的问题，挂载自己的阿里云盘后，在tvbox （影视TV 2.1.6）播放，没有“原画”选项。
而且加载速度不稳定，偶尔10M，其他都是100K以内。
我会持续再观察下

**Comment by outcastveron** [comment]
发现是EXO的问题，选择IJK就有原话而且速度很快。IJK字幕支持差点

**Comment by LeeeMooo** [comment]
@outcastveron 你好，

> https://alist.nn.ci/tool/aliyundrive/request.html 中选 use my own client，输入自己的app id和App Secret，重新获取自己的opentoken

这一步报错无效clientid
<img width="762" alt="image" src="https://github.com/power721/alist-tvbox/assets/23691333/58f841ff-2c8e-42ed-8ccf-1c95f27d8e18">
是这样配置吗

**Comment by outcastveron** [comment]
配置界面，高级设置，开放token认证url 选择https://openapi.alipan.com/oauth/access_token
填写自己的app id和App Secret
最后把生成的token在账号更新
重启
