### ISSUE TITLE
挂载多个阿里云盘失败，请大佬帮着看一下

### ISSUE THREAD

**Issue by outcastveron** [power721/alist-tvbox#154]
所有的token都是即时生成的，有些盘可以挂载，有的则失效，同一账号下的备份盘资源盘可能只能挂载其一
主观看盘正常

alist 日志如下

ERRO [2024-01-12 09:53:32] failed list /📀我的阿里云盘/XXXXXXXXXXXXXXX/资源盘: driver not init
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
/app/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
/app/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
/app/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
/app/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
/app/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
/app/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
/app/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
/app/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
/app/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
/usr/lib/go/src/net/http/server.go:2938
net/http.(*conn).serve
/usr/lib/go/src/net/http/server.go:2009
runtime.goexit
/usr/lib/go/src/runtime/asm_amd64.s:1650
failed get objs
[GIN] 2024/01/12 - 09:53:32 | 200 | 742.626µs | 172.104.98.156 | POST "/api/fs/list"

**Comment by power721** [comment]
看不出来，只有重启试试

**Comment by outcastveron** [comment]
好的，感谢回复

**Comment by liuyaboixixi** [comment]
解决了嘛
