### ISSUE TITLE
安装几次都是同样错误,invalid client id, 然后too many requests

### ISSUE THREAD

**Issue by ysuolmai** [power721/alist-tvbox#157]
Log如下,重装 换机器都是一样的结果

[33mWARN [2024-01-16 09:50:56] not enable search
INFO [2024-01-16 09:50:56] total 161 enabled storages
INFO [2024-01-16 09:50:56] initStorage PikPakShare /每日更新/PikPak
INFO [2024-01-16 09:50:56] Init PikPakShare /每日更新/PikPak
INFO [2024-01-16 09:50:56] Store PikPakShare /每日更新/PikPak
INFO [2024-01-16 09:50:56] initStorage AliyundriveShare2Open /电影/欧美/未分类-4
INFO [2024-01-16 09:50:56] Init AliyundriveShare2Open /电影/欧美/未分类-4
INFO [2024-01-16 09:50:56] refreshToken 1 https://auth.alipan.com/v2/account/token
INFO [2024-01-16 09:50:58] Open API Client ID:
INFO [2024-01-16 09:50:58] refreshOpenToken 1 https://api.xhofe.top/alist/ali_open/token false
ERRO [2024-01-16 09:50:59] refreshOpenToken error: failed to refresh open token: invalid client_id
INFO [2024-01-16 09:50:59] Store AliyundriveShare2Open /电影/欧美/未分类-4
INFO [2024-01-16 09:50:59] initStorage AliyundriveShare2Open /电影/欧美/系列
INFO [2024-01-16 09:50:59] Init AliyundriveShare2Open /电影/欧美/系列
INFO [2024-01-16 09:50:59] refreshOpenToken 1 https://api.xhofe.top/alist/ali_open/token false
ERRO [2024-01-16 09:51:00] refreshOpenToken error: failed to refresh open token: invalid client_id
INFO [2024-01-16 09:51:00] Store AliyundriveShare2Open /电影/欧美/系列
INFO [2024-01-16 09:51:00] initStorage AliyundriveShare2Open /电影/欧美/演员系列
INFO [2024-01-16 09:51:00] Init AliyundriveShare2Open /电影/欧美/演员系列
INFO [2024-01-16 09:51:01] refreshOpenToken 1 https://api.xhofe.top/alist/ali_open/token false
ERRO [2024-01-16 09:51:02] refreshOpenToken error: failed to refresh open token: invalid client_id
INFO [2024-01-16 09:51:02] Store AliyundriveShare2Open /电影/欧美/演员系列
INFO [2024-01-16 09:51:02] initStorage AliyundriveShare2Open /电影/港台
INFO [2024-01-16 09:51:02] Init AliyundriveShare2Open /电影/港台
INFO [2024-01-16 09:51:03] refreshOpenToken 1 https://api.xhofe.top/alist/ali_open/token false
ERRO [2024-01-16 09:51:03] refreshOpenToken error: failed to refresh open token: invalid client_id

然后就是

ERRO [2024-01-16 09:52:33] refreshOpenToken error: failed to refresh open token: Too Many Requests
INFO [2024-01-16 09:52:33] Store AliyundriveShare2Open /电影/2023
INFO [2024-01-16 09:52:33] initStorage AliyundriveShare2Open /电影/泰国
INFO [2024-01-16 09:52:33] Init AliyundriveShare2Open /电影/泰国
[GIN] 2024/01/16 - 09:52:33 | 200 | 113.711µs | 127.0.0.1 | GET "/api/public/settings"
[GIN] 2024/01/16 - 09:52:34 | 200 | 95.819µs | 127.0.0.1 | GET "/api/public/settings"
INFO [2024-01-16 09:52:35] refreshOpenToken 1 https://api.xhofe.top/alist/ali_open/token false
ERRO [2024-01-16 09:52:35] refreshOpenToken error: failed to refresh open token: Too Many Requests
INFO [2024-01-16 09:52:35] Store AliyundriveShare2Open /电影/泰国
INFO [2024-01-16 09:52:35] initStorage AliyundriveShare2Open /电影/按导演和演员/【著名西方演员电影】
INFO [2024-01-16 09:52:35] Init AliyundriveShare2Open /电影/按导演和演员/【著名西方演员电影】
[GIN] 2024/01/16 - 09:52:36 | 200 | 119.687µs | 127.0.0.1 | GET "/api/public/settings"
[GIN] 2024/01/16 - 09:52:36 | 200 | 121.031µs | 127.0.0.1 | GET "/api/public/settings"
INFO [2024-01-16 09:52:37] refreshOpenToken 1 https://api.xhofe.top/alist/ali_open/token false
ERRO [2024-01-16 09:52:37] refreshOpenToken error: failed to refresh open token: Too Many Requests

**Comment by power721** [comment]
你的账号open token不是从AList网站获取的，和ALIst的认证url不匹配。
假设是从webdev获取的，在设置页面-》高级功能-》开放Token认证URL-》选择
https://aliyundrive-oauth.messense.me/oauth/access_token
点击更新
重启服务

**Comment by ysuolmai** [comment]
感谢大佬,搞定了!

**Comment by death4444** [comment]
我来补一发手把手教程：
首先检查问题：
![Screenshot_2024-10-07-15-39-05-148_org telegram messengers](https://github.com/user-attachments/assets/a21a4c0c-d3e3-48db-af27-19b9d3b3aca5)
发现问题，token获取的通道不对，这个报错说明我选择了APP通道，但是获取的是alist的token：
![image](https://github.com/user-attachments/assets/dcd3e3d4-b3d3-413a-b4aa-cc020180a184)
改正设置：
![小雅报错failed get objs failed to list objs driver not init](https://github.com/user-attachments/assets/cf11ccf0-bbb1-4cd2-9969-2fc0da330cb3)
点击更新
重启服务
![image](https://github.com/user-attachments/assets/036ca8dd-c1da-46da-a608-2156bafd3375)
