### ISSUE TITLE
更新到最新版（2024.1.19）的xiaoya-tvbox不能正常使用

### ISSUE THREAD

**Issue by zhijianjianghu** [power721/alist-tvbox#158]
进入小雅alist,进入子目录下提示“failed get objs: failed to list objs: driver not init”，具体的xiaoya-tvbox容器的docker日志如下：
![20240119194558289](https://github.com/power721/alist-tvbox/assets/157119137/13dc837b-db57-45e9-b1e6-1f8bfef7c116)，请问怎么解决这一问题？

**Comment by power721** [comment]
重启，看看alist日志

**Comment by zhijianjianghu** [comment]
> 重启，看看alist日志

已经重启
![20240119200027102](https://github.com/power721/alist-tvbox/assets/157119137/bca1993c-36ca-4f48-b09e-93db6b5857b7)

**Comment by power721** [comment]
账号里面重新配置一下token

**Comment by zhijianjianghu** [comment]
好的，我刷新下令牌

**Comment by ashakii** [comment]
一样的问题，我的是n1当旁路由，搞2天了，之一是这个问题，刷新token也没用

**Comment by zhijianjianghu** [comment]
> 账号里面重新配置一下token

大佬，刷新令牌了，问题还是提示“failed get objs: failed to list objs: driver not init”
![Uploading 20240119201939671.jpg…]()

**Comment by power721** [comment]
管理界面下载日志发来

**Comment by zhijianjianghu** [comment]
> 管理界面下载日志发来

![20240119202640673](https://github.com/power721/alist-tvbox/assets/157119137/3ecf33ea-5c61-4222-a16c-727d391004cd)
佬，在管理界面那下载不了日志，还有其他方式下日志吗？

**Comment by power721** [comment]
怎么下载不了？

**Comment by zhijianjianghu** [comment]
> 怎么下载不了？

点击日志下载，就出错
![Uploading 20240119202640673.jpg…]()

**Comment by power721** [comment]
截屏alist日志页面

**Comment by zhijianjianghu** [comment]
> 截屏alist日志页面

![20240119205030696](https://github.com/power721/alist-tvbox/assets/157119137/551a977a-ad92-41d8-ba54-9f654b279644)
![20240119205107145](https://github.com/power721/alist-tvbox/assets/157119137/1af70a6c-e69c-413d-b493-89a97285588f)
![20240119205123780](https://github.com/power721/alist-tvbox/assets/157119137/0c90c30f-1d5f-4e60-b07e-e0ef30aeb463)
佬，我前中后截图了三张，前面显示token遗失，后面显示驱动不能加载

**Comment by power721** [comment]
账号有选择主账号吗？

**Comment by zhijianjianghu** [comment]
没有

**Comment by power721** [comment]
要打开才行

**Comment by zhijianjianghu** [comment]
那好，我打开重启下容器

**Comment by zhijianjianghu** [comment]
> 要打开才行

佬，可以了，感谢！顺便问一句，下载日志提示错误
![image](https://github.com/power721/alist-tvbox/assets/157119137/637146ac-c829-4fc7-8fcf-7c6ae36a7d6f)
这是什么原因，是代理原因吗？

**Comment by power721** [comment]
看不出来

**Comment by zhijianjianghu** [comment]
> 看不出来

好的，感谢大佬耐心解答！

**Comment by xingyue1104** [comment]
> 管理界面下载日志发来

我也是这个问题怎么解决
