### ISSUE TITLE
请问大佬，播放地址乱码要怎么解决？

### ISSUE THREAD

**Issue by intelsong** [power721/alist-tvbox#162]
![image](https://github.com/power721/alist-tvbox/assets/58145562/24a54019-9130-47d4-a1e5-e066c93fae7d)
![image](https://github.com/power721/alist-tvbox/assets/58145562/0be7d093-8421-483e-afd9-ff0fb4365436)
我看了一下，站点数据也是这样，请问要怎么设置？

**Comment by power721** [comment]
有什么问题？

**Comment by intelsong** [comment]
![image](https://github.com/power721/alist-tvbox/assets/58145562/310636c2-85e6-4361-875e-ae93744cc030)
我看到你的json数据是正确显示了vod_id的值
![image](https://github.com/power721/alist-tvbox/assets/58145562/eec714b8-a1f4-42ea-988f-f181fc31493b)

**Comment by power721** [comment]
都是这样显示的。没有问题，不需要改。

**Comment by intelsong** [comment]
象我这样有强迫症的人看了不舒服，应该可以解决吧，是字符编码和解码的问题吧
