### ISSUE TITLE
希望大佬在后续版本中增加多密钥支持

### ISSUE THREAD

**Issue by WudaxStudio** [power721/alist-tvbox#167]
如题，目前Power大佬给出的安全订阅是单独的。
但是由于使用中，有些情况需要给亲戚家的人临时使用一下，这样的话存在以下问题：
1、如果给亲戚家临时使用后，他会记住我的安全密钥。
2、如果我修改密钥，会导致我家里使用的设备都需要重新修改密钥，如我的手机，我的好几个电视都要更新。
所以希望大佬更新**多密钥支持**
就是可以添加2个或者2个以上的安全密钥，这样的话，我只需要把临时密钥给亲戚临时用下就行了。后期我也可以方便的停用或者修改那个密钥。感谢大佬！

**Comment by WudaxStudio** [comment]
这里说的亲戚，是一个代名词，生活中总会遇到一个不喜欢的人，但是他要用一下，你又不能不给，所以给他一个临时用一下。

**Comment by power721** [comment]
学会拒绝^_^

**Comment by WudaxStudio** [comment]
> 多个安全Token，逗号分割

谢谢大佬，哈哈哈^_^

**Comment by power721** [comment]
好像有问题，不能用

**Comment by WudaxStudio** [comment]
嗯嗯，看大佬你又更新了，现在可以用了

Harold ***@***.***> 于2024年1月25日周四 11:33写道：
