### ISSUE TITLE
不支持

### ISSUE THREAD

**Issue by happymy** [power721/alist-tvbox#168]
不支持

_Originally posted by @power721 in https://github.com/power721/alist-tvbox/issues/166#issuecomment-1908116917_
            
请问有其他替代软件么？ MAC M2没有可用的安卓模拟器。

**Comment by power721** [comment]
https://github.com/catvod/CatVodOpen/releases

**Comment by happymy** [comment]
还有其他的么？MAC上软件崩溃，win上添加了tvbox的配置地址：http://xxx:4567/sub/0。没反应。谢谢。

**Comment by power721** [comment]
vidhub

**Comment by happymy** [comment]
vidhub不能添加tvbox配置地址。tvbox的xiaoya没开启alist的webdav。还有其他软件么？M2芯片没有安卓虚拟机，痛苦。。

**Comment by power721** [comment]
webdav是支持的啊

**Comment by happymy** [comment]
WebDAV端口5678 都是默认的。。。
访问不了。还有其他软件么？麻烦您了。

**Comment by power721** [comment]
WebDAV端口是5344。

**Comment by happymy** [comment]
挂上了，空的。算了放弃了。直接用网页看吧。没有海报墙。等大神把tvbox移植到多平台。

**Comment by power721** [comment]
![IMG_1580](https://github.com/power721/alist-tvbox/assets/2384040/3bbb14f0-871f-4b5e-b460-ec1e0df9128e)

**Comment by happymy** [comment]
去掉路径/dav。挂上空的。不去掉找不到服务器。。。可能不兼容吧。

**Comment by happymy** [comment]
加上密码guest_Api789正常了。不过没有海报墙。算了。。。

**Comment by happymy** [comment]
还需要自己继续添加到媒体库。我真的放弃了。他是去刮削。。。我怕我云盘黑户。。。真的谢谢你。我还是用网页看吧。
