### ISSUE TITLE
请问怎么削刮 自己添加的站点？

### ISSUE THREAD

**Issue by intelsong** [power721/alist-tvbox#170]
就是想把自己加站点上的电影和豆瓣数据关联，在影视仓能看到影片信息，比如简介之类的

**Comment by intelsong** [comment]
能不能这样：我默认的小雅站用你的内置削括，自已添加的站点可在索引的电影数据中手动添加或者修改削括信息？

**Comment by power721** [comment]
纯净版随便你改

**Comment by intelsong** [comment]
好的，谢谢，我先试试看

**Comment by intelsong** [comment]
> 纯净版随便你改

我没在你文档中找到这纯净版，纯净版是不是又叫独立版？
