### ISSUE TITLE
安装好纯净版后，电影数据为空，只能删除不能添加

### ISSUE THREAD

**Issue by intelsong** [power721/alist-tvbox#171]
![image](https://github.com/power721/alist-tvbox/assets/58145562/cd5e691f-00a0-4f94-931f-6c4381a18698)

**Comment by power721** [comment]
可以添加

**Comment by intelsong** [comment]
![image](https://github.com/power721/alist-tvbox/assets/58145562/4e921f8c-5782-4c24-8acf-c211f43cf1c3)
每次都要手动刷新一下网页才能出添加按钮

**Comment by power721** [comment]
修复了
