### ISSUE TITLE
请求支持zyplayer

### ISSUE THREAD

**Issue by happymy** [power721/alist-tvbox#172]
zyplayer是跨平台的tvbox。请求支持。
我配置过，不成功。应该就差一点。格式什么的问题。
请大佬帮我看看。

**Comment by power721** [comment]
支持了

**Comment by happymy** [comment]
请问是那个仓库的zyplay ？
求配置地址的配置图。

**Comment by power721** [comment]
![image](https://github.com/power721/alist-tvbox/assets/2384040/5112c3c4-1d0f-484f-a5ad-0164cc5f6b86)

**Comment by power721** [comment]
https://github.com/Hiram-Wong/ZyPlayer

**Comment by happymy** [comment]
点检测也过了。

但是片库空的，网络请求失败，请手动刷新。

**Comment by happymy** [comment]
成了！还要设置成默认的。。。

**Comment by happymy** [comment]
高兴早了，还是不能播放。
请问还要对这个软件配置什么？
M2 CPU。

**Comment by power721** [comment]
那就是播放器的问题了。
我Linux系统测试有些视频不能播放。

**Comment by happymy** [comment]
好像所有电影都不能放，文件就没有到云盘里。

**Comment by Joker-lm** [comment]
> 所有都不能放，文件就没有到云盘里。

不好用，播放器不行，好多都播放不了

**Comment by happymy** [comment]
可能是之前刮削导致云盘暂时黑名单，今早恢复了。
