### ISSUE TITLE
接口怎么配置给猫影视？

### ISSUE THREAD

**Issue by Joker-lm** [power721/alist-tvbox#178]
如题，已经搭建好了，影视什么的已经在用，就是想问下作者或者各位大佬，怎么把这个接口配置给猫影视，配置格式是什么？感谢感谢！！！

**Comment by power721** [comment]
更新最新版

**Comment by taikani** [comment]
打开4567接口出现502 Bad Gateway 怎么解决？

**Comment by letheva1** [comment]
> 更新最新版

请教大佬，猫影视是在订阅里，猫影视配置接口：http://alist:alist@yourip:4567/open，这个地址吗？
配置后，可以看到分类列表，但显示加载分类失败

**Comment by letheva1** [comment]
解决了，换了1.12就可以了
