### ISSUE TITLE
猫影视接口找不到自己添加的alist套娃

### ISSUE THREAD

**Issue by foxdodo** [power721/alist-tvbox#186]
用的小雅版，在后台添加了自己的alist站点，用安卓手机端tvbox套壳类的app和网页端都可以看到alist套娃地址，但是用ios的猫影视无法找到套娃alist链接

**Comment by power721** [comment]
在云盘里面啊

**Comment by power721** [comment]
升级最新版试试

**Comment by power721** [comment]
站点里面把url改成https://xiaoya.example.com:8443
