### ISSUE TITLE
外网访问不显示图片

### ISSUE THREAD

**Issue by linrong123** [power721/alist-tvbox#189]
架设在自己家里，通过nginx反代。内网访问一切正常，外网也能正常播放，就是不显示图片。不知道要做什么特别的设置吗。
![微信图片_20240201195020](https://github.com/power721/alist-tvbox/assets/57894830/f590bcd0-d090-4112-babc-648724344ad7)

**Comment by power721** [comment]
是不是你的ip被豆瓣屏蔽了

**Comment by linrong123** [comment]
确实是我自己的问题- -换了个ip可以了。估计刮削太多被禁了。
