### ISSUE TITLE
能否让tvbox调用的小雅不是5344端口

### ISSUE THREAD

**Issue by lehhair** [power721/alist-tvbox#192]
同标题，我配置了两个域名，将5344端口反代到另一个域名了，但是tvbox的订阅依旧是访问tvbox域名：5344的，我用的是集成版，我看到可以在管理处添加站点，但是那样还要额外设置索引文件

**Comment by power721** [comment]
站点修改url就行了

**Comment by lehhair** [comment]
> 站点修改url就行了

请问是把集成版默认带的http://localhost改成我反代后的域名地址就可以了吗，感谢大佬回复
