### ISSUE TITLE
大佬好，请教如何删除内置已添加的所有数据源，只保留“本地”和“Alist”？

### ISSUE THREAD

**Issue by Jimmiliang** [power721/alist-tvbox#194]
我安装的是纯净版，配置了自己的Alist网盘资源，把订阅链接添加到TVBOX后，发现多出了很多数据源，我想将红框的这类数据源全部删除，只保留自己配置的网盘内容，我需要一个真正的纯净版，未配置任何数据的，请教大老该如何实现呢？
![{4B4E71E8-4721-4693-A498-C1851452CFBD}](https://github.com/power721/alist-tvbox/assets/158617554/67fbaae3-d1a1-4015-a602-5527aca6d771)

**Comment by power721** [comment]
配置url输入无效的，比如http://localhost/

**Comment by power721** [comment]
如果想加电视直播和去掉BiliBili，在定制里面：
```json
{
    "lives":[
        {
            "name":"live",
            "type":0,
            "url":"https://xhdwc.tk/tvlive.txt",
            "playerType":1,
            "epg":"http://epg.112114.xyz/?ch={name}&date={date}",
            "logo":"https://epg.112114.xyz/logo/{name}.png"
        }
    ],
  "sites-blacklist": ["csp_BiliBili"]
}
```

**Comment by Jimmiliang** [comment]
> 配置url输入无效的，比如 http://localhost/

我TVBOX里配置的是订阅里的“TvBox配置地址”，不是站点列表里的“URL地址”，然而里边包含了除我配置网盘资源以外，还有非常多的内置数据源，我是想把这些默认内置的数据源全部删除掉，只留我自己的就行。

我找遍管理后台，没找到您上边说的“定制”，是在哪个入口下的？

**Comment by Jimmiliang** [comment]
> 配置url输入无效的，比如 http://localhost/

我TVBOX里配置的是订阅里的“TvBox配置地址”，不是站点列表里的“URL地址”，然而里边包含了除我配置网盘资源以外，还有非常多的内置数据源，我是想把这些默认内置的数据源全部删除掉，只留我自己的就行。

**Comment by Jimmiliang** [comment]
> 如果想加电视直播和去掉BiliBili，在定制里面：
> 
> ```json
> {
>     "lives":[
>         {
>             "name":"live",
>             "type":0,
>             "url":"https://xhdwc.tk/tvlive.txt",
>             "ua":"okhttp/3.15",
>             "playerType":1,
>             "epg":"http://epg.112114.xyz/?ch={name}&date={date}",
>             "logo":"https://epg.112114.xyz/logo/{name}.png"
>         }
>     ],
>   "sites-blacklist": ["csp_BiliBili"]
> }
> ```

我想去掉所有，不只是BiliBili这个，只保留“本地”和"Alist"就行，要怎么写定制呢？

**Comment by power721** [comment]
![image](https://github.com/power721/alist-tvbox/assets/2384040/489d9830-4af1-473b-a3f3-1df7abcfeeae)

**Comment by power721** [comment]
配置url输入http://localhost/，就会只保留3个站源。

**Comment by Jimmiliang** [comment]
> 配置url输入 [http://localhost/，就会只保留3个站源。](http://localhost/%EF%BC%8C%E5%B0%B1%E4%BC%9A%E5%8F%AA%E4%BF%9D%E7%95%993%E4%B8%AA%E7%AB%99%E6%BA%90%E3%80%82)

我需要外网使用，配置了http://localhost/这个地址，外网无法访问资源吧？
