### ISSUE TITLE
docker部署，alist日志无法查看 

### ISSUE THREAD

**Issue by LiteCoder** [power721/alist-tvbox#196]
首先感谢提供好用的整合功能，反馈两个小问题：

1. 点击alist日志，出现错误提示

![截图20240203172412](https://github.com/power721/alist-tvbox/assets/1974044/217b8d0e-55a5-462f-8b63-ae8111fcdbd3)

日志文件默认应该是这个路径：
`/opt/alist/data/log/log.log`

2. 另外发现xiaoya数据无法更新，每次要手动删除alist目录，重启alist-tvbox；然后看启动日志立才有重新下载tvbox.zip

**Comment by power721** [comment]
日志路径是/opt/alist/log/log.log

**Comment by power721** [comment]
重新运行安装脚本更新

**Comment by LiteCoder** [comment]
> 重新运行安装脚本更新

`docker run -itd -p 4567:4567 -p 5344:80 --restart=unless-stopped -v /volume1/docker/xiaoya-tvbox:/data -v /volume1/docker/xiaoya-tvbox/alist:/opt/alist/data -v /volume1/docker/xiaoya-tvbox/atv:/opt/atv/data --name=xiaoya-tvbox haroldli/xiaoya-tvbox:latest`
不是shell脚本安装的，挂载的目录有没有问题？

**Comment by LiteCoder** [comment]
> 把/opt/alist/log/alist.log挂载到/opt/alist/log/log.log 增加一条直接挂载这个文件而不是目录

可以了没想到可以直接挂载文件。谢谢解答！
