### ISSUE TITLE
大佬下午好，我已经挂载好阿里云盘，网页里能看到网盘内容，但后台都什么都没有喔？

### ISSUE THREAD

**Issue by Jimmiliang** [power721/alist-tvbox#197]
安装的纯净版，挂载好阿里云盘后，网页前端是能正常观看网盘内容，但想对该挂载的网盘进行管理一下，进入后台却是一片空白。
![{C0B51B31-1721-499b-86DC-9033A6999381}](https://github.com/power721/alist-tvbox/assets/158617554/a24ecfa9-4390-4086-9506-b2af2eb23cb7)
![{468D18B2-0326-44f7-9970-3EE1105AB931}](https://github.com/power721/alist-tvbox/assets/158617554/0a12793a-2255-4c5c-b386-b17c55941cf6)

**Comment by power721** [comment]
修复

**Comment by Jimmiliang** [comment]
> 修复

我是通过重装去修复吗？

**Comment by power721** [comment]
是
