### ISSUE TITLE
关于TMDB剧集的刮削

### ISSUE THREAD

**Issue by xinxinenjoy** [power721/alist-tvbox#206]
多季的剧集在文件夹里会以
/主目录/第一季
/主目录/第二季
这样的路径放置文件

1.但是通过索引刮削之后只能识别到/主目录这一层，TVBOX点进去是空的。
2.增加索引深度或者把多季度的文件放在同一文件夹内也有其他问题，如图所示：
![自动2024-02-10_00-38-18](https://github.com/power721/alist-tvbox/assets/119488608/a66b97cf-f421-4995-a3d2-6c9f380d101b)
怎么样才能让多季度的文件显示在一个海报内，打开之后
![自动2024-02-09_17-45-00](https://github.com/power721/alist-tvbox/assets/119488608/4b53a97c-55ab-47fd-b451-fbed1e86d105)
让它像这个里边的123456可选？

**Comment by power721** [comment]
/主目录/第一季/1.mkv
/主目录/第一季/2.mkv
/主目录/第一季/3.mkv
/主目录/第二季/1.mkv
/主目录/第二季/2.mkv
/主目录/第二季/3.mkv
...

**Comment by xinxinenjoy** [comment]
> /主目录/第一季/1.mkv /主目录/第一季/2.mkv /主目录/第一季/3.mkv /主目录/第二季/1.mkv /主目录/第二季/2.mkv /主目录/第二季/3.mkv ...

试了按季去索引目录刮出不来东西，还是没理解具体的用法

**Comment by power721** [comment]
24小时
https://www.alipan.com/s/cvhCPaZXASt
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by xinxinenjoy** [comment]
问题已经解决，目录就正常放置刮削即可
找到原因是因为我之前添加了.mp3的主题曲文件，删除就全正常了
