### ISSUE TITLE
/🈴我的阿里分享/Tacit0924 失效了，能不能修复一下？

### ISSUE THREAD

**Issue by intelsong** [power721/alist-tvbox#208]

**Comment by power721** [comment]
没有失效啊，一直能用

**Comment by intelsong** [comment]
![image](https://github.com/power721/alist-tvbox/assets/58145562/4f6045f4-331b-4de3-970e-a6d72f66d0da)
不能用

**Comment by intelsong** [comment]
![image](https://github.com/power721/alist-tvbox/assets/58145562/f8f031e8-2aa5-4053-8c02-140b6606e2e1)
