### ISSUE TITLE
docker_address.txt不再生效，/tvbox/juhe.json多仓配置无效

### ISSUE THREAD

**Issue by Rain113113** [power721/alist-tvbox#21]
/tvbox/juhe.json多仓配置无效

**Comment by Rain113113** [comment]
docker_address.txt不再生效，使用订阅链接会自动识别   都不自动识别  高级设置里面已经设置了的  不会识别

**Comment by power721** [comment]
[订阅界面添加多仓链接](https://github.com/power721/alist-tvbox/commit/0747998f838015998cf491d8373d73152cf5c901)

**Comment by Rain113113** [comment]
/tvbox/juhe.jso订阅地址  跳转的tvbox/my.json界面里面的DOCKER_ADDRESS没变 所以还是.....用不了

**Comment by power721** [comment]
兄弟能看一下中文文档吗
