### ISSUE TITLE
路径中有空格的应该如何在别名和 Categories 中设置？

### ISSUE THREAD

**Issue by mikexfreeze** [power721/alist-tvbox#213]
![微信截图_20240218100224](https://github.com/power721/alist-tvbox/assets/16068816/48b15899-1fee-4b46-b7cd-468f5e57d3b6)
如图，尝试使用%20 直接使用空格 以及转义符 都不行，想使用双引号但是有校验。

**Comment by power721** [comment]
直接使用空格

**Comment by mikexfreeze** [comment]
> 直接使用空格

Thanks 找到问题了天线宝宝资源没了，米奇妙妙屋两个空格 😂
