### ISSUE TITLE
报告一个小bug

### ISSUE THREAD

**Issue by intelsong** [power721/alist-tvbox#215]
TMDB电影数据列表和豆瓣电影列表中用TMDB刮削的电影，直接点路径会出错，路径多了一个斜杠
![image](https://github.com/power721/alist-tvbox/assets/58145562/c4c7c7df-27f1-44f6-9980-75e555eb6dc4)

**Comment by power721** [comment]
你改了站点url？

**Comment by intelsong** [comment]
我没有改，这个是我的自建alist站点

**Comment by intelsong** [comment]
已经知道是什么原因了：我自建站点url为：http://192.168.118.118:5244/，这样就不行，把最后的“/”去掉就好了，老大应该做个判断，对这个“/”处理：如果url最后面有"/"，那后面的路径最前面就不用加“/”
