### ISSUE TITLE
用荷城茶秀的接口播放地址是正常显示，用alist-tvbox接口后播放地址显示为乱码

### ISSUE THREAD

**Issue by intelsong** [power721/alist-tvbox#220]
![image](https://github.com/power721/alist-tvbox/assets/58145562/9833edee-8198-42dc-8377-66455d7d93fa)
![image](https://github.com/power721/alist-tvbox/assets/58145562/61b360c7-4702-41b5-b6c2-5189ed77ee36)

虽然不影响使用，但是对于有强迫症的我来说，总是感觉多那么一点，老大能不能想一下办法修正？

**Comment by power721** [comment]
换一个播放器，影视TV

**Comment by power721** [comment]
安装开发版

**Comment by intelsong** [comment]
你不是说开发版不更新了吗？
