### ISSUE TITLE
请教一下关于转存文件夹的问题

### ISSUE THREAD

**Issue by gosky-yyk** [power721/alist-tvbox#226]
**描述**
现在不能自定义转存文件夹吗，我看文档描述会自动创建转存文件夹，但是现在的表现是并没有自动创建转存文件夹而是将所有的转存文件存储在资源库的根目录下，我的建议是否可以在界面上可以配置用来管理转存文件夹的id。

**环境**
 - 系统平台：Docker
 - 版本模式： 小雅版
 - 版本号： 415.1814

**Comment by gosky-yyk** [comment]
刚才我开了一下日志，确实有创建文件夹的操作，只是权限不足
![1708481702583](https://github.com/power721/alist-tvbox/assets/66851882/9fee047a-d6d9-424b-9f16-9c0a4f081279)

**Comment by gosky-yyk** [comment]
刚才我看了一下日志，确实有创建临时缓存目录的操作，只是权限不足的问题创建失败，是否需要配置什么呢？
![1708481702583](https://github.com/power721/alist-tvbox/assets/66851882/7bb80f91-49b7-44ac-bc62-812de8b491c7)

**Comment by gosky-yyk** [comment]
不仅仅是创建临时缓存目录出现权限问题，删除文件也出现该问题

**Comment by power721** [comment]
重新弄一下账号token

**Comment by gosky-yyk** [comment]
我尝试过更新token，但是还是依旧

**Comment by power721** [comment]
要么账号token和open token不是同一个账号
要么open token没有授权

**Comment by gosky-yyk** [comment]
token和open token应该是同一个账号的，我从localStorage复制复制出来的，其他同学的都是正常的吗

**Comment by gosky-yyk** [comment]
解决了，自己申请了开发者账号，重新授权token时候选择所有权限，然后获取access_token和refresh_token即可
