### ISSUE TITLE
2月21号更新后，猫影视可以加载出播放列表了，但是还是不能播放，没更新前播放列表都加载不出

### ISSUE THREAD

**Issue by jianlongfan** [power721/alist-tvbox#231]
2月21号更新后，猫影视可以加载出播放列表了，但是还是不能播放，没更新前播放列表都加载不出
![mao](https://github.com/power721/alist-tvbox/assets/32221537/8c21b89d-57fd-4350-89c1-beb2b6072288)

**Comment by jianlongfan** [comment]
为什么我的不行😂，配置应该没头问题，我用安卓端的TVBOX是可以播放的，用猫影视就是播放不了。

**Comment by jianlongfan** [comment]
![90228AB3-E882-4FC0-85C6-426EEBC08FD3](https://github.com/power721/alist-tvbox/assets/32221537/57763e61-f774-4d87-9bda-8e6b64a78bfa)

**Comment by power721** [comment]
出错了，进管理后台看日志啊

**Comment by power721** [comment]
使用内置的猫影视配置接口可以工作

**Comment by jianlongfan** [comment]
日志
![日志](https://github.com/power721/alist-tvbox/assets/32221537/8af638d4-e078-4160-b4e7-341eef4155e5)

**Comment by jianlongfan** [comment]
可能找到原因了，我的外网只能用IPV6访问。端口用了反向代理，把小雅的5344端口反向代理到15344端口用于外网访问，但是影视猫还是用的5344端口。大佬能修复一下吗？
![AB5FE35F-4426-47C1-8175-CB2AC9734391](https://github.com/power721/alist-tvbox/assets/32221537/15844bd9-c861-4af4-9cec-ad2cffa3d2f9)

**Comment by jianlongfan** [comment]
搞定了，把http://localhost地址改成外网地址就可以了。
