### ISSUE TITLE
索引，刮削都已有但是站点中搜索不到是什么原因，针对挂载的阿里云盘上的资源

### ISSUE THREAD

**Issue by mikexfreeze** [power721/alist-tvbox#233]
![image](https://github.com/power721/alist-tvbox/assets/16068816/e1986cd8-9281-4829-9349-582de127d130)
![image](https://github.com/power721/alist-tvbox/assets/16068816/d49428c1-576c-4fe9-83e0-b0ec1a1f8d46)
如图只能搜索到丫仙女站点本身的资源

**Comment by power721** [comment]
网页不支持

**Comment by mikexfreeze** [comment]
Thanks
