### ISSUE TITLE
分类怎么隐藏站点名称那个选项

### ISSUE THREAD

**Issue by livilivi** [power721/alist-tvbox#236]
已经配置了category.txt
但tvbox在首页后面、所有分类的前面还是会显示一个站点名 比如默认的“🎞️丫仙女”
然后里面是文件列表
这个分类选项有办法隐藏吗，还是希望在电视只看海报墙

**Comment by power721** [comment]
配置页面，关闭海报墙混合模式

**Comment by livilivi** [comment]
> 配置页面，关闭海报墙混合模式

关闭后，默认的站点分类还在，不过内容变成了海报墙，这是预期的效果么？

不过这对我来说足够了，非常感谢。
