### ISSUE TITLE
索引路径中有加号(+)时，提示‘失效路径’

### ISSUE THREAD

**Issue by zfr000** [power721/alist-tvbox#241]
索引路径中有加号(+)时，被替换成了空格，导致索引时‘失效路径’错误。

例如此路径：/🈴我的阿里分享/Tacit0924/【更新中的】和完结的电视剧.动漫.电影.综艺纪录片/【 剧 l 集 】/【电 l 视 l 剧】和完结的/【国产电视剧】合集1500多部(39TB)/【国产电视剧】1500部 41T/特种兵电视剧系列4部全+电影四部

**Comment by zfr000** [comment]
![Snipaste_2024-02-26_15-59-27](https://github.com/power721/alist-tvbox/assets/32825519/bf511721-1ae9-4e5c-8788-99bc1cbc906a)

**Comment by power721** [comment]
修复
