### ISSUE TITLE
最新版本的影视仓客户端的视频都无法观看，显示加载失败。

### ISSUE THREAD

**Issue by xdfx1180** [power721/alist-tvbox#247]
**环境**
 - 系统平台：[e.g. Linux]
 - TvBox：[e.g. 影视仓]
 - 版本模式： [e.g. host网络]
 - 版本号： [e.g.424.2057 ]

**Comment by power721** [comment]
可以播放。
自己看看日志什么错误

**Comment by liujuntao123** [comment]
遇到了了同样的问题，但看日志没问题，应该是影视仓的问题

**Comment by liujuntao123** [comment]
似乎找到原因了，跟https有关

**Comment by ddclaus** [comment]
> 似乎找到原因了，跟https有关

老兄解决了吗？我也遇到类似问题，TVBOX添加小雅配置源后所有节目都有索引，就是都不能播放。丫仙女目录为空。更新©️ v.0306.0337(B)版本后发生的。

**Comment by xdfx1180** [comment]
> > 似乎找到原因了，跟https有关
> 
> 老兄解决了吗？我也遇到类似问题，TVBOX添加小雅配置源后所有节目都有索引，就是都不能播放。丫仙女目录为空。更新©️ v.0306.0337(B)版本后发生的。

最近的两个版本我测试是可以的

**Comment by xdfx1180** [comment]
> > 似乎找到原因了，跟https有关
> 
> 老兄解决了吗？我也遇到类似问题，TVBOX添加小雅配置源后所有节目都有索引，就是都不能播放。丫仙女目录为空。更新©️ v.0306.0337(B)版本后发生的。

最近AList - TvBox的两个版本我测试是可以的

**Comment by hdfr99-AF8888** [comment]
> 似乎找到原因了，跟https有关

怎么解决呢，我在手机上可以播放，但是在电视上就不行了
