### ISSUE TITLE
进入配置页面有时会出现浮动错误信息，还有应用日志中有503错误

### ISSUE THREAD

**Issue by sobigworm** [power721/alist-tvbox#248]
这个错误好像是进入配置页面时获取更新日志时出现的，不知道是不是网络问题

![20240228173837](https://github.com/power721/alist-tvbox/assets/114928942/382d1b33-934b-48aa-a49c-136930a747ea)

这个503错误就不知道是什么原因了，好像也没什么影响

![20240228174956](https://github.com/power721/alist-tvbox/assets/114928942/90dd414d-2c2a-4c80-9648-956978c06e56)
![20240228175026](https://github.com/power721/alist-tvbox/assets/114928942/e43d4f69-048c-49d7-8faf-70f5a81c726d)

**Comment by power721** [comment]
忽略这些错误
