### ISSUE TITLE
请问群晖7.2 docker host模式怎么改默认端口运行？

### ISSUE THREAD

**Issue by ck629** [power721/alist-tvbox#249]
bridge模式不能联网不知道为什么，就只能用host了，但是默认的80端口用不了，怎么把4567和80改成别的？
我使用container manager管理容器，不使用ssh

**Comment by power721** [comment]
创建容器的时候配置端口映射。
自己查看最新文档。

**Comment by power721** [comment]
端口是4567和5678，改不了

**Comment by power721** [comment]
4567端口可以更改。
1. 在挂载的/data目录创建文件夹config。
2. 新建一个文件application-host.yaml
内容：
```yaml
server:
  port: 6789
```
3. 重启容器

**Comment by ck629** [comment]
> 4567端口可以更改。
> 
> 1. 在挂载的/data目录创建文件夹config。
> 
> 2. 新建一个文件application-host.yaml
> 
> 内容：
> 
> ```yaml
> 
> server:
> 
>   port: 6789
> 
> ```
> 
> 3. 重启容器

感谢大佬回复，请问默认的80端口可以改吗？

**Comment by power721** [comment]
没有80端口

**Comment by ck629** [comment]
> 没有80端口

![image](https://github.com/power721/alist-tvbox/assets/9910024/4e3883cd-5d2e-4368-a2b3-9e2bb6d16e28)

有80端口冲突报错

**Comment by power721** [comment]
host模式使用5678端口。
你没有选host网络？

**Comment by ck629** [comment]
> host模式使用5678端口。
> 你没有选host网络？

选了啊，就很神奇

**Comment by power721** [comment]
你不是用的hostmode镜像？

**Comment by ck629** [comment]
> 你不是用的hostmode镜像？

感谢您的耐心回复。
docker container manager的注册表里面只有haroldli/xiaoya-tvbox，我是下载后选的host网络，应该增加什么参数来使用host镜像？

**Comment by power721** [comment]
镜像有不同的tag，下载的时候应该会让你选择

**Comment by ck629** [comment]
> 镜像有不同的tag，下载的时候应该会让你选择

需要手输标签，默认是latest，需要输入什么才能是hostmode镜像？

**Comment by power721** [comment]
hostmode

https://hub.docker.com/r/haroldli/xiaoya-tvbox/tags

**Comment by ck629** [comment]
> hostmode
> https://hub.docker.com/r/haroldli/xiaoya-tvbox/tags
好的，再次感谢
