### ISSUE TITLE
同步电影数据始终无法完成

### ISSUE THREAD

**Issue by outcastveron** [power721/alist-tvbox#253]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [ ] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [ ] 我确定没有重复的issue或讨论。
- [ ] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [ ] 我确定这个问题在最新版本中没有被修复。

**描述**
刮削IMDB后，同步电影数据始终进行。

**步骤**
重现问题的步骤:

**期望的结果**
简单描述你期望的结果。

**截图**
![image](https://github.com/power721/alist-tvbox/assets/39554024/38bf8399-0d6c-4823-b83c-eab7668659db)

**日志**
问题相关日志。

**环境**
 - 系统平台：Linux [e.g. Linux / ARM]
 - TvBox：影视TV[e.g. 影视TV、影视仓、宝盒]
 - 版本模式： 集成版[e.g. 集成版、独立版、host网络、native版]
 - 版本号：430.1841 [e.g. 417.1942]

**其它**

**Comment by power721** [comment]
手动点击同步按钮试试

**Comment by outcastveron** [comment]
偶尔会成功，基本上跑24小时就会被自动更新给取消了，先这么用把
