### ISSUE TITLE
tvbox小雅–教育–儿童合集中的资源加载不出来

### ISSUE THREAD

**Issue by silas3082** [power721/alist-tvbox#256]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [x] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [x] 我确定没有重复的issue或讨论。
- [x] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [x] 我确定这个问题在最新版本中没有被修复。

**描述**
tvbox小雅–教育–儿童合集中的资源加载不出来，显示没找到数据。其他资源比如同一个教育目录下，外语、公考等目录可以正常加载出来。

**步骤**
重现问题的步骤:
1.打开tvbox
2. 将首页数据源设置为Alist或者雅仙女
3. 点击“教育”–“儿童合集”目录
4. 出现没有找到数据

**期望的结果**
简单描述你期望的结果。

**截图**
问题相关截图。

**日志**
问题相关日志。

**环境**
 - 系统平台：手机
 - TvBox：[tvbox com.github.tvbox.osc.tk]
 - 版本模式： [nas版]
 - 版本号： [1.0.20240228_0117]

**其它**

**Comment by power721** [comment]
重启不行找小雅
