### ISSUE TITLE
猫影视配置无法覆盖内置的配置

### ISSUE THREAD

**Issue by kingsey** [power721/alist-tvbox#258]
参考文档用my.json合并来自定义猫影视配置后不满意，想恢复原来的配置，复制原来的配置到/etc/xiaoya/cat/config_open.json后执行同步，但日志显示的仍是读取/www/cat/my.json 并merge cat config，猫影视配置接口获取到的也是之前合并之后的内容。

应用版本：432.2157

**Comment by power721** [comment]
删除my.json

**Comment by kingsey** [comment]
> 删除my.json

没有my.json  删掉了，他把config当my读……

**Comment by kingsey** [comment]
![image](https://github.com/power721/alist-tvbox/assets/9674563/be4693b8-b4a7-412f-934c-ba3dd7d6ca8a)
![image](https://github.com/power721/alist-tvbox/assets/9674563/2d6a5f47-1bc8-4cfb-98be-114925db4b3c)

**Comment by kingsey** [comment]
> 重启一下

好了，更新版本之后能正确替换了
