### ISSUE TITLE
内置默认订阅文件绕开了安全订阅设置

### ISSUE THREAD

**Issue by 10api** [power721/alist-tvbox#259]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [1 ] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [1 ] 我确定没有重复的issue或讨论。
- [ 1] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [ 1] 我确定这个问题在最新版本中没有被修复。

**描述**
在tvbox文件夹内默认存在四个订阅文件：my.json，my_ext.json，juhe.json，juhe_ext.json，外部可以直接访问，在app上测试可以连接

**步骤**
重现问题的步骤:

**期望的结果**
简单描述你期望的结果。

**截图**
问题相关截图。

**日志**
问题相关日志。

**环境**
 - 系统平台：[e.g. Linux / ARM]
 - TvBox：[e.g. 影视TV、影视仓、宝盒]
 - 版本模式： [e.g. 集成版、独立版、host网络、native版]
 - 版本号： [e.g. 417.1942]

**其它**

**Comment by 10api** [comment]
小雅集成版
应用版本：437.1430

**Comment by power721** [comment]
但是无法访问alist

**Comment by 10api** [comment]
添加订阅时，是否以这四个默认文件读取写入呢

**Comment by 10api** [comment]
那么多仓订阅的就是默认juhe.json吗，

**Comment by power721** [comment]
是的

**Comment by 10api** [comment]
那么xxx_ext.json这两个相当于备份文件?

**Comment by power721** [comment]
没有使用
