### ISSUE TITLE
"parses"字段是否可以加一个自定义隐藏

### ISSUE THREAD

**Issue by 10api** [power721/alist-tvbox#262]
"parses"解析接口可能由于自带的接口失效无法使用，看前排问题您的回复是手动去自定义一个文件，单独为了这个去自定义创建比较麻烦，建议和自定义隐藏订阅一样加一个隐藏解析，可以通过"parses"的"name"隐藏，应该不同的解析不会设置同一个名字

**Comment by power721** [comment]
升级到最新版
