### ISSUE TITLE
订阅里面的直播源，我的私用如何去掉

### ISSUE THREAD

**Issue by as564335sa** [power721/alist-tvbox#266]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

订阅里的直播源，因为我没有iptv.m3u文件，里面的url打开是这个
![image](https://github.com/power721/alist-tvbox/assets/35949162/18c68ac9-a3c2-485f-8f4a-09a5f238d1a3)
导致订阅源放到TVBOX里一直转圈读不出来，问下这个不用的话有什么方法能去掉这一项么

**Comment by sobigworm** [comment]
大佬一般都比较高冷，言简意赅，小白都理解不了，我也是小白，我这有解决方法
去掉这项比较麻烦，这里就不说了。
其实你的问题是某些tvbox客户端默认获取第一个直播源，如果第一个直播源失效或者是错误的，就会造成直播失效的，必须手动切换直播源才能解决的问题，也有些tvbox客户端没有切换功能

解决的方法很简单，在xiaoya-tvbox后台订阅页面点击编辑，在定制中输入下面的内容，就可以替换掉我的私用里面的url直播链接，q版tvbox不支持.m3u格式直播源，你也可以自己替换为可以使用的.txt直播源

{
 "lives":[
  {
   "name":"我的私用",
   "type":0,
   "url":"https://live.fanmingming.com/tv/m3u/ipv6.m3u",
   "playerType":1,
   "ua":"okhttp/3.15",
   "epg":"http://epg.112114.xyz/?ch={name}&date={date}",
   "logo":"https://epg.112114.xyz/logo/{name}.png"
  }
 ]
}

**Comment by power721** [comment]
新版修复了这个问题，文件不存在会自动移除我的私用

**Comment by as564335sa** [comment]
> 大佬一般都比较高冷，言简意赅，小白想要理解有点难度，我也是小白，我这有解决方法 去掉我的私用这项比较麻烦，要修改默认文件，这里就不说了。 其实你的问题是某些tvbox客户端默认获取第一个直播源，如果第一个直播源失效或者是错误的，就会造成直播失效的，必须手动切换直播源才能解决的问题，也有些tvbox客户端没有切换功能
> 
> 解决的方法很简单，在xiaoya-tvbox后台订阅页面点击编辑，在定制中输入下面的内容，就可以替换掉我的私用里面的url直播链接，q版tvbox不支持.m3u格式直播源，你也可以自己替换为可以使用的.txt直播源
> 
> { "lives":[ { "name":"我的私用", "type":0, "url":"https://live.fanmingming.com/tv/m3u/ipv6.m3u", "playerType":1, "ua":"okhttp/3.15", "epg":"http://epg.112114.xyz/?ch={name}&date={date}", "logo":"https://epg.112114.xyz/logo/{name}.png" } ] }

确实，感谢大佬

**Comment by as564335sa** [comment]
更新了确实修改了，感谢大佬
