### ISSUE TITLE
订阅里面没有站点里的地址怎么回事呀

### ISSUE THREAD

**Issue by tsiens** [power721/alist-tvbox#267]
看各种教程，默认是Y仙女，然后tvbox里面就有丫仙女，
我的4567页面站点里面是本地、资源小站，
然后4567/sub/0订阅里面里面，并没有本地、资源小站呀？tvbox里面也不显示这两？
bilibili我也登录了，tvbox也没显示我的帐号内容，
求救

**Comment by tsiens** [comment]
站点里面的
![image](https://github.com/power721/alist-tvbox/assets/24999801/0e846028-ce7a-4f4b-b7ab-fe260f52283c)
订阅链接里找不到资源小站
![image](https://github.com/power721/alist-tvbox/assets/24999801/cd50d27c-9076-40de-acc7-1ab16a38c224)

**Comment by power721** [comment]
选择TvBox第二个站源，观看三方站点内容。或者在我的套娃观看。

**Comment by tsiens** [comment]
> 选择TvBox第二个站源，观看三方站点内容。或者在我的套娃观看。

大佬。第二个是ALIST吧？里面空的哇
![16397ed6d947abf72ab142d61c42777](https://github.com/power721/alist-tvbox/assets/24999801/3ec71909-acad-4557-b53b-6fdc7592a5e3)

**Comment by tsiens** [comment]
![image](https://github.com/power721/alist-tvbox/assets/24999801/99592846-0ebc-43a1-b01b-e1e1a2a0150f)
解决问题了，我是内网开的http，然后外网用https转发的。但是生成的订阅文件里面的jar还是http无法访问的。
这里开启就好了

**Comment by ChinaToby** [comment]
> > 选择TvBox第二个站源，观看三方站点内容。或者在我的套娃观看。
> 
> 大佬。第二个是ALIST吧？里面空的哇 ![16397ed6d947abf72ab142d61c42777](https://private-user-images.githubusercontent.com/24999801/315916244-3ec71909-acad-4557-b53b-6fdc7592a5e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODAxMjgsIm5iZiI6MTcyODc3OTgyOCwicGF0aCI6Ii8yNDk5OTgwMS8zMTU5MTYyNDQtM2VjNzE5MDktYWNhZC00NTU3LWI1M2ItNmZkYzc1OTJhNWUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YmNlOTFkNjM0NDU3MjZiNGRkMjc4NzI5NDdiNWIxODA4YWIwMzc3NDZlNWI0Y2YyNDEzMmZmNmVjMjg1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EFO3zzCEkamdrBA3DtI-mqkwpSxxU3yd_sU1SHMlKuA)
> 
> B站也是空的 ![image](https://private-user-images.githubusercontent.com/24999801/315922597-9e41c41c-630e-47e9-bbb7-1daf69984ab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODAxMjgsIm5iZiI6MTcyODc3OTgyOCwicGF0aCI6Ii8yNDk5OTgwMS8zMTU5MjI1OTctOWU0MWM0MWMtNjMwZS00N2U5LWJiYjctMWRhZjY5OTg0YWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZWY3OTVhOGVlZGEyNmM1ZWEzMzkzYzY2NTRkNGZhYjA4ZmY1ZjM1NDRhM2Q3ZDk5ZTMzZGM5ZjY3OWVmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pHVViJvu1QGU7DaEmfWqWK-M_pHVdEnbpKQX-c6s9Po) ![image](https://private-user-images.githubusercontent.com/24999801/315922372-343d0bb5-64a3-44a9-b7a0-1fc614bf1c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODAxMjgsIm5iZiI6MTcyODc3OTgyOCwicGF0aCI6Ii8yNDk5OTgwMS8zMTU5MjIzNzItMzQzZDBiYjUtNjRhMy00NGE5LWI3YTAtMWZjNjE0YmYxYzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNjgyZGY3MmYxM2UwNTU3ZWQ0NDA0MWU5Y2E2NmQwNmUwODI0YjNmNDJlOWY2N2ZjYTMzNjYwMzBhNzBlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hs9u8OcugkWtz2wwhQNLZBWXlhFzjj1VK4AUJWQKthQ)

安装完之后，我的首页 小雅那儿最初能看到目录，后来 就变成了 登录Alist的登录框，看不到那些资源目录了
不知道我说明白了没有
![Snipaste_2024-10-13_08-45-17](https://github.com/user-attachments/assets/48f2b09e-0bd3-4398-8fde-043a0b8339c1)
