### ISSUE TITLE
账号配置丢失

### ISSUE THREAD

**Issue by lazebird** [power721/alist-tvbox#271]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [x] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [x] 我确定没有重复的issue或讨论。
- [x] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [x] 我确定这个问题在最新版本中没有被修复。

**描述**
系统启动时docker自动启动，账号信息加载不进来；手动重启容器后加载正常；基本从我开始用这个就有这个问题，近1个月吧，问题有点奇怪，不确定是否是软件bug，希望能够有进一步的排查方法或解决方法，希望寻求大家帮助，多谢
加载失败日志如下
2024-03-24T11:11:57.830+08:00 INFO 58 --- [main] c.h.alist_tvbox.service.AccountService : load account from files
2024-03-24T11:11:57.833+08:00 WARN 58 --- [main] c.h.alist_tvbox.service.AccountService : No account
账号文件如下：myopentoken.txt mytoken.txt
lqy@lqy-pc:/mnt/c/Users/lazeb$ ll /etc/xiaoya/
total 65472
drwxr-xr-x  6 lqy  lqy      4096 Mar 12 00:13 ./
drwxr-xr-x 74 root root     4096 Mar 24 11:21 ../
drwxr-xr-x  3 lqy  lqy      4096 Mar 18 22:34 atv/
-rw-r--r--  1 lqy  lqy  66940928 Mar 24 02:55 atv.mv.db
-rw-r--r--  1 lqy  lqy     58679 Mar 16 21:17 atv.trace.db
drwxr-xr-x  2 lqy  lqy      4096 Mar 12 00:12 backup/
-rw-r--r--  1 lqy  lqy         2 Mar 10 22:37 folder_type.txt
drwxr-xr-x  3 lqy  lqy      4096 Mar 23 23:51 index/
drwxr-xr-x  2 lqy  lqy      4096 Mar 24 00:00 log/
-rw-r--r--  1 lqy  lqy       336 Mar 11 00:08 myopentoken.txt
-rw-r--r--  1 lqy  lqy        33 Mar 10 23:47 mytoken.txt
-rw-r--r--  1 lqy  lqy        42 Mar 11 00:08 temp_transfer_folder_id.txt

**步骤**
重现问题的步骤:
重启系统，等待docker启动后进入http://localhost:4567/#/accounts 查看账号信息，发现缺失；查看日志发现找不到账号

**期望的结果**
自动启动后能正常使用

**截图**
<img width="1866" alt="image" src="https://github.com/power721/alist-tvbox/assets/12560868/1d22278e-57b8-40f7-9b20-07ae1b639afc">

**日志**
见描述

**环境**
 - 系统平台：win11最新版+wsl ubuntu+docker
 - TvBox：NA
 - 版本模式：一键部署(小雅版)
 - 版本号：应用版本：444.1913

**其它**
无

**Comment by lazebird** [comment]
手动重启后账号加载正常
<img width="1870" alt="image" src="https://github.com/power721/alist-tvbox/assets/12560868/be43453d-c4fc-4b50-867d-4ed8618a5e68">

**Comment by power721** [comment]
有没有挂载/etc/xiaoya目录到docker的/data目录？

**Comment by lazebird** [comment]
> 有没有挂载/etc/xiaoya目录到docker的/data目录？

是指出问题的时候吗？这个我要晚点回家检查下
我是用一键安装脚本直接安装的，还有手动重启正常的话应该是有挂载正常的；出问题的时候的情况我晚上补充下截图看看
多谢帮忙

**Comment by lazebird** [comment]
![image](https://github.com/power721/alist-tvbox/assets/12560868/ba246fc6-bca3-4a6b-bce2-c515b1d65cbe)
出问题时命令行看/data数据有些异常，可能是什么原因导致的呢？

**Comment by lazebird** [comment]
我试试看能不能docker延迟启动类的

**Comment by lazebird** [comment]
没有解决，目前看应该是系统启动的时候挂载文件失败了，有什么办法或建议吗

**Comment by lazebird** [comment]
docker desktop降到4.24.2后没问题，应该和alist这边没关系，等待新版本修复
