### ISSUE TITLE
我不想自动删除阿里云盘上的缓存，我把它调成0，点击更新，刷新一下网页，它又变回900，

### ISSUE THREAD

**Issue by GonewtwLyb** [power721/alist-tvbox#294]
![1](https://github.com/power721/alist-tvbox/assets/89258817/bb5794b3-c8ae-4492-991f-c199477ef3af)

**Comment by fulujun** [comment]
请问一下这个是怎么解决的，目前还是会自动会重新变回900

**Comment by power721** [comment]
实际值是0,显示错误
