### ISSUE TITLE
cn.har01d.alist_tvbox.service.IndexService.getRemoteVersion()" is null 报错

### ISSUE THREAD

**Issue by liyiranlab** [power721/alist-tvbox#299]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [x] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [x] 我确定没有重复的issue或讨论。
- [x] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [x] 我确定这个问题在最新版本中没有被修复。

**描述**
打开tvbox配置就报下面错误：
Cannot invoke "String.trim()" because the return value of "cn.har01d.alist_tvbox.service.IndexService.getRemoteVersion()" is null

**期望的结果**
这是什么问题？要怎么解决？

**截图**
问题相关截图。

**日志**
问题相关日志。

**环境**
 - 系统平台：[e.g. Linux / ARM armbian]
 - TvBox：[e.g. 影视TV、影视仓、宝盒]
 - 版本模式： [e.g. 集成版]
 - 应用版本：480.2024
 - 本地版本：[480.2021](http://192.168.10.206:4567/#/meta)

**其它**

**Comment by power721** [comment]
访问我的网站去获取最新索引版本，有时候网络问题连不上。
忽略这个错误。
