### ISSUE TITLE
如何更新小雅版本，旧版本已经很久 了

### ISSUE THREAD

**Issue by UnicornZhang** [power721/alist-tvbox#343]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [ ] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [ ] 我确定没有重复的issue或讨论。
- [ ] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [ ] 我确定这个问题在最新版本中没有被修复。

**描述**
简单描述你遇到的问题。

**步骤**
重现问题的步骤:

**期望的结果**
简单描述你期望的结果。

**截图**
问题相关截图。

**日志**
问题相关日志。

**环境**
 - 系统平台：[e.g. Linux / ARM]
 - TvBox：[e.g. 影视TV、影视仓、宝盒]
 - 版本模式： [e.g. 集成版、独立版、host网络、native版]
 - 版本号： [e.g. 417.1942]

**其它**

**Comment by gitcook** [comment]
SSL 过期了 ？

**Comment by power721** [comment]
自己编的Alist，小雅的版本号没有什么用。只有部分配置文件和分享数据用的小雅的。
