### ISSUE TITLE
tvbox 能否适配 115 网盘直链播放

### ISSUE THREAD

**Issue by jackbba** [power721/alist-tvbox#345]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [ ✔] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [ ✔] 我确定没有重复的issue或讨论。
- [✔ ] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [✔ ] 我确定这个问题在最新版本中没有被修复。

**描述**
简单描述你遇到的问题。
小雅 docker alist  支持阿里网盘秒传 115 网盘直链播放，我有 115 会员播放非常流畅，tvbox 能否适配， 阿里云盘秒转 115 播放功能，谢谢🙏

**期望的结果**
简单描述你期望的结果。
 
h 大大，tvbox 能否适配 小雅 docker，阿里秒转  115 网盘的直链播放，谢谢

**Comment by power721** [comment]
没看到有这个功能

**Comment by ranapankj** [comment]
> 没看到有这个功能

![233](https://github.com/power721/alist-tvbox/assets/30015771/e32602e2-dd1b-44be-b5b0-c5d997369912)

**Comment by jackbba** [comment]
> 没看到有这个功能

【小雅115和夸克的玩法-哔哩哔哩】 https://b23.tv/O07plok，楼下哪位兄弟也说了，不知道 tvbox 能不能也支持 115，突破阿里的限制🚫

**Comment by jackbba** [comment]
> 没看到有这个功能

小雅115和夸克的玩法-哔哩哔哩】 https://b23.tv/O07plok

楼下哪位兄弟也说了，不知道 tvbox 能不能也支持 115，突破阿里的限制🚫
