### ISSUE TITLE
关于新版小雅可以使用115网盘直连 和  夸克资源的问题

### ISSUE THREAD

**Issue by Jacksonqing** [power721/alist-tvbox#348]
新版小雅可以用115网盘和夸克资源  这个配置的txt文件说要放到小雅目录下  请问在xiaoya-tvbox重要如何操作？

**Comment by Jacksonqing** [comment]
看说明应该放到小雅的配置目录下  但是好像不起作用  是不是xiaoya-tvbox内置的小雅版本不够新的原因？

**Comment by fengci** [comment]
蹲个答案

**Comment by csanmm887123** [comment]
同样急需这个功能，阿里云已经开始限速了

**Comment by wabhmgxz** [comment]
小雅的转存不能直接放在自己的硬盘上吗？
