### ISSUE TITLE
订阅JSON里面有个jar字段没有把http换成https

### ISSUE THREAD

**Issue by BenzLeung** [power721/alist-tvbox#36]
如下截图。是我哪里没有配置正确吗？

<img width="737" alt="图片" src="https://github.com/power721/alist-tvbox/assets/2764768/b29e8ac0-41eb-4a54-879c-54eaaac49774">

**Comment by power721** [comment]
nginx反代配置有问题。

**Comment by power721** [comment]
可以加一个跳转
```
server {
    if ($host = xxx.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name tv.har01d.cn;

    listen 80;
    return 404; # managed by Certbot
}
```

**Comment by aries1998** [comment]
我这种通过cf反代的只支持https的没法这么改，不过这个问题通过脚本处理下生成个json文件倒可以解决

另外有个必须改代码的问题是这个返回豆瓣数据的cgi， 返回数据里面应该是https，现在都是http

![image](https://github.com/power721/alist-tvbox/assets/4135555/a1eb29a0-5c3b-432d-a1ee-744a47cbb07f)

![image](https://github.com/power721/alist-tvbox/assets/4135555/c0109536-b259-427e-b2ab-753df54948fb)

**Comment by power721** [comment]
那需要加一个配置项，开启https

**Comment by BenzLeung** [comment]
> 

用这个配置的前提是服务器能正常用80和443，域名后面不用加端口号。而我这是普通家用宽带，开不了80和443，所以域名后面加了 `:8888`。

我用的不是nginx而是caddy，nginx不知道但是caddy无法在一个端口上同时提供http和https服务。

是不是等待大佬的下一版本就好了呢？

**Comment by power721** [comment]
新版本，在设置页面 -> 高级设置里面开启HTTPS。
```bash
wget https://d.har01d.cn/update_xiaoya.sh -O update_xiaoya.sh && sh ./update_xiaoya.sh -t native
```

**Comment by aries1998** [comment]
docker repo上的镜像不对吧， 对比了下docker repo里面和本地的镜像，是一致的， 但是那个配置页面一直提示有新版本，也确实看不到你说的这个配置

![image](https://github.com/power721/alist-tvbox/assets/4135555/84e162d4-1cf4-4b77-92d7-d4941ea941ab)

**Comment by BenzLeung** [comment]
> 新版本，在设置页面 -> 高级设置里面开启HTTPS。
> 
> ```shell
> wget https://d.har01d.cn/update_xiaoya.sh -O update_xiaoya.sh && sh ./update_xiaoya.sh -t native
> ```


这个 `-t native` 版本运行不了，报错信息：

```
/lib/ld-musl-x86_64.so.1: atv: Not a valid dynamic program
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.2023-08-01T09:44:53.610610533Z replace token? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

这几行信息循环了好多次。

换回来 `-t latest` 就正常了。

另外我认真阅读了大佬你的文档，发现了定制json替换功能：

```
{
    "replace": {
      "http://我的域名:8888/spring.jar": "https://我的域名:8888/spring.jar" 
    },
    "sites-blacklist": ["说明1","说明2", "说明3","说明4","公告", "ext_live_protocol", "cc"],
    "sites": [
     
    ]
}
```

但是似乎 `replace` 对jar字段不生效？如果能让它生效，也就解决问题了，而且还能同时兼容内网 `http://192.168.1.x:4567` 和外网 `https://域名:8888` 访问。

**Comment by power721** [comment]
native只支持Linux平台，不支持arm平台

**Comment by BenzLeung** [comment]
我的不是arm，是win11+docker，x64 [捂脸]

**Comment by power721** [comment]
win也需要装Linux虚拟机

**Comment by BenzLeung** [comment]
`-t native` 死活搞不起来，我还是等待 latest 吧，不着急。

或者大佬可以先让定制json替换 `replace` 功能支持jar字段吗？

**Comment by BenzLeung** [comment]
dev版本成功了，感谢大佬。

**Comment by power721** [comment]
已经合并到latest
