### ISSUE TITLE
jar的标题识别有些许问题

### ISSUE THREAD

**Issue by DieRose** [power721/alist-tvbox#37]
![1](https://github.com/power721/alist-tvbox/assets/55175055/0c894ade-2701-4368-9c9f-ea21cfc6fa55)
![2](https://github.com/power721/alist-tvbox/assets/55175055/40e2b5fa-fa1e-4474-975b-a5741605188c)
其他的还有集数显示不对 比如3集识别成2集 而且标题也不对

**Comment by power721** [comment]
jar没有做标题识别。后台处理了标题，去掉了相同部分。你直接用浏览模式看看这些文件名是什么
