### ISSUE TITLE
这两天更新了，新聚合地址tvbox不能播放小雅的视频以及搜索到的阿里分享了

### ISSUE THREAD

**Issue by smerckzak** [power721/alist-tvbox#39]
我试了“文件”里面添加小雅alist是可以播放的，
但是搜索里面小雅的视频有速度，但是几秒钟以后就显示播放错误。而视频也会存到我色网盘。试了好几个版本的tvbox都是这样。。。之前这些版本是可以正常播放的

**Comment by smerckzak** [comment]
刚才下载最新7.30的版本，聚合地址repo/0无法解析，sub/0地址正常

**Comment by power721** [comment]
直接在网页打开聚合地址看看。
你用的什么tvbox，影视仓吗？什么版本？

**Comment by smerckzak** [comment]
影视仓5。0可以加入聚合地址，但是涉及到网盘视频，都是有下载速度播放错误，tv box加聚合地址无法连接，sub地址可以用。pluto也是这样

**Comment by smerckzak** [comment]
网页聚合地址打开都是链接啊。看着没问题

**Comment by smerckzak** [comment]
![Screenshot_2023-08-01-18-50-43-085_com microsoft emmx beta](https://github.com/power721/alist-tvbox/assets/64113248/b0c58d00-4206-4e1a-a18a-342e049c0a9f)

**Comment by smerckzak** [comment]
![IMG_20230801_194400](https://github.com/power721/alist-tvbox/assets/64113248/88d4d3d9-24c9-4838-bb86-21374fabebca)

**Comment by power721** [comment]
换repo/1试试

**Comment by smerckzak** [comment]
聚合地址连

> 换repo/1试试

换repo/1还是一样的

**Comment by power721** [comment]
影视仓有问题，换影视TV、宝盒、q版TvBox、takagen99 TvBox都行。

**Comment by smerckzak** [comment]
> 影视仓有问题，换影视TV、宝盒、q版TvBox、takagen99 TvBox都行。
我试一下这些，谢谢大佬。

**Comment by smerckzak** [comment]
大佬影视TV找不到😂😂
添加聚合地址，takagen99最新版无法解析
月光宝盒也是无法解析，改成订阅地址sub/0正常
q版TVbox是不是那种tvboxpro？连订阅地址都无法读取了，可能我1。03版本太低了

**Comment by power721** [comment]
影视TV:
https://github.com/FongMi/TV/releases
宝盒 不是月光宝盒: 
https://t.me/bh_tvbox
q版TVbox:
https://github.com/o0HalfLife0o/TVBoxOSC/releases

**Comment by smerckzak** [comment]
> 影视TV: https://github.com/FongMi/TV/releases 宝盒 不是月光宝盒: https://t.me/bh_tvbox q版TVbox: https://github.com/o0HalfLife0o/TVBoxOSC/releases

谢谢大佬的地址了👍👍影视TV倒是都没问题了，宝盒没宝就是月光宝盒啊，tg我看不了，不过作者都是宝盒没宝。tvboxosc跟takagen一样，聚合不能解析，只能使用订阅了。

**Comment by AdmiralLickSugar** [comment]
我昨天也折腾了一晚上，只有影视TV能播放，但我把容器环境变量里面小雅alist的端口该为了我自己挂载的也就是由5344改为5678了，并且把install=xiaoya这个环境变量删除后，现在任何一个手机app都能正常播放小雅的内容了（还需要在tvbox-xiaoya那里将站点指定到alist）
![d982d10b4bc5c6a5217d5930da56b578](https://github.com/user-attachments/assets/5ac89564-8566-42d1-bf33-ccef22d86c8f)
![Uploading d0078e316b4540a45ed439b37aff5896.jpg…]()
