### ISSUE TITLE
搜索索引问题

### ISSUE THREAD

**Issue by mtyzaq** [power721/alist-tvbox#4]
1，添加订阅0到TVBOX，挂载的Alist网盘把文件删除了，在TVBOX搜索中还能搜到，点击提示没有找到数据。
这个索引文件怎么更新
2，自己修改站点后配置保存在什么位置？修改DOCKER配置就恢复出厂了，还要再重新设置

**Comment by power721** [comment]
1. 更新索引是一个成本很高的事，如果用的xiaoya版，就等xiaoya更新后重启docker容器。xiaoya版的索引文件是/index/index.video.txt, 索引版本在/version.txt
2. 我刚刚更新了docker，数据库存在/data目录。本地运行java项目，数据库在~/.config/atv
