### ISSUE TITLE
夸克/uc网盘webdav无法播放问题

### ISSUE THREAD

**Issue by liyanglan** [power721/alist-tvbox#401]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [x] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [x] 我确定没有重复的issue或讨论。
- [x] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [x] 我确定这个问题在最新版本中没有被修复。

**描述**
修复夸克/uc网盘webdav无法播放问题

**步骤**
重现问题的步骤:
无论是TV-BOX或者OK影视客户端添加的:我的夸克分享；还是在海报墙打开夸克资源都无法播放，提示错误。

**期望的结果**
修复夸克/uc网盘webdav无法播放问题

**环境**
 - 系统平台：[Linux]
 - TvBox、影视TV
 - 版本模式： [host网络]
 - 版本号： [616.2117]

**Comment by power721** [comment]
检查一下是不是cookie过期了

**Comment by power721** [comment]
修复了，更新试试
