### ISSUE TITLE
打扰了，想问一下哪个版本的tvbox支持emby

### ISSUE THREAD

**Issue by dogxgit** [power721/alist-tvbox#428]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [ √ ] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [ √ ] 我确定没有重复的issue或讨论。
- [ √ ] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [ √ ] 我确定这个问题在最新版本中没有被修复。

**描述**
想问一下哪个版本的tvbox支持emby

**步骤**
我试了一下takagen99版本的tvbox，能看到影视封面，但是点击进去是空白页。在emby客户端是可以正常显示和播放的。

**期望的结果**
想问一下哪个版本的tvbox支持emby

**截图**
问题相关截图。

**日志**
问题相关日志。

**环境**
 - TvBox：[takagen99]

**Comment by power721** [comment]
影视TV
OK影视

**Comment by dogxgit** [comment]
谢谢大佬！
