### ISSUE TITLE
删除容器重建后，原始数据还在，请问怎样可以彻底清空数据重新搭建呢？

### ISSUE THREAD

**Issue by Lxsx-c** [power721/alist-tvbox#431]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [√] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [√] 我确定没有重复的issue或讨论。
- [√] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [√] 我确定这个问题在最新版本中没有被修复。

**描述**
删除容器重建后，原始数据还在，请问怎样可以彻底清空数据重新搭建呢？
原始数据指的是例如用户名我修改过，不是admin，重新搭建后依然不是admin，还有豆瓣电影数据列表里之前刮削过的，但是路径已经变化了的数据依然存在。或者说有什么办法可以一键删除掉之前刮削过的但是路径已经失效了的数据？

**Comment by power721** [comment]
删除文件夹/etc/xiaoya
