### ISSUE TITLE
部分视频无法播放，现象为TVBOX提示：获取播放信息错误，前端提示：failed link: failed get link: No Permission to access resource File

### ISSUE THREAD

**Issue by Lxsx-c** [power721/alist-tvbox#449]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [√] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [√] 我确定没有重复的issue或讨论。
- [√] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [√] 我确定这个问题在最新版本中没有被修复。

**描述**
部分视频无法播放，现象为TVBOX提示：获取播放信息错误，前端提示：failed link: failed get link: No Permission to access resource File

**截图**
![image](https://github.com/user-attachments/assets/ae7be696-0fe6-42be-88f5-080a22e8c92e)
![image](https://github.com/user-attachments/assets/9f663c5d-0fa7-4c4c-a30d-1db2adc97f25)
![image](https://github.com/user-attachments/assets/511f0185-1896-4f46-935f-b93a4422410a)

**日志**
INFO [2024-09-21 20:27:22] 获取文件直链 01.mkv 65a6682fc56e2a10e4c345b3b724722a432cec27 528786599
INFO [2024-09-21 20:27:23] 请求结果 : {"responses":[{"body":{"code":"ForbiddenNoPermission.File","message":"No Permission to access resource File"},"id":"0","status":403}]}
ERRO [2024-09-21 20:27:23] 保存文件失败 : No Permission to access resource File
ERRO [2024-09-21 20:27:23] failed link /🈴我的阿里分享/Tacit0924/【剧a集】/【剧丨集】更新中和完结的/【更新中】电视剧/】1【/1完结的/19层 [科幻 悬疑 冒险][孙千 魏哲鸣]/01.mkv: No Permission to access resource File
failed get link

**环境**
 - 系统平台：群晖NAS
 - TvBox：官方版
 - 版本模式： 集成版
 - 版本号：630.0727

**Comment by power721** [comment]
重启试试

**Comment by money114** [comment]
你是否用了阿里tv认证的token而又没有相关的权益，换回alist认证就好了
