### ISSUE TITLE
打开强制登录后提示禁用来宾账户

### ISSUE THREAD

**Issue by zadishu** [power721/alist-tvbox#46]
![1](https://github.com/power721/alist-tvbox/assets/110985414/f70d82a4-62fd-420c-9779-16571ee8bfc8)
用的默认的账号密码

**Comment by power721** [comment]
打开强制登录，就在配置界面看用户名和密码是什么

**Comment by power721** [comment]
用户名是dav

**Comment by zadishu** [comment]
密码是什么啊？

**Comment by power721** [comment]
guest_Api789

**Comment by power721** [comment]
用户名和密码都可以自己改

**Comment by power721** [comment]
用默认用户名和密码，开强制登录的意义是什么？

**Comment by zadishu** [comment]
不开强制登陆，打开小雅这个提示，账号也登陆了
![Uploading IMG_7209.png…]()

**Comment by zadishu** [comment]
failed link: failed get link: BadRequest:fileId: 不能为空

**Comment by power721** [comment]
有问题发日志给我
