### ISSUE TITLE
failed link: failed get link: BadRequest:fileId: 不能为空

### ISSUE THREAD

**Issue by zadishu** [power721/alist-tvbox#47]
播放器提示，根据提示看是没有填写转存文件ID，但是又找不到在哪填写，已经创建过文件下
![image](https://github.com/power721/alist-tvbox/assets/110985414/53f395da-0762-43e9-9936-d0a87c97816c)

**Comment by power721** [comment]
你用的哪个版本？

**Comment by zadishu** [comment]
他自己好了，关闭问题
