### ISSUE TITLE
Tvbox 网页版

### ISSUE THREAD

**Issue by hansen0730** [power721/alist-tvbox#49]
本以为是tvbox网页版，目前只计划提供alist服务？ 有计划实现tvbox网页版吗，没看到有人实现

**Comment by hansen0730** [comment]
另外docker container 里 默认的 DNS 不对 导致 wget 会失败

**Comment by power721** [comment]
AList自带网页播放器

**Comment by power721** [comment]
网页直接用阿里看了，网页播放器解码能力差
