### ISSUE TITLE
建议启动脚本添加github代理。

### ISSUE THREAD

**Issue by happymy** [power721/alist-tvbox#497]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [x] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [ ] 我确定没有重复的issue或讨论。
- [ ] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [x] 我确定这个问题在最新版本中没有被修复。

由于众所周知的原因，中国大陆地区的用户，在启动容器时，下载zip数据包会失败。#485

建议：容器启动后从github gitlab githubusercontent 下载zip数据包时增加使用代理mirror.ghproxy.com。

**Comment by liyanglan** [comment]
别加了吧，速度太慢，需要的话自己修改下就行了

**Comment by happymy** [comment]
我可以自己改init.sh。 可有时候一天更新好几个版本。
应该不会对速度用太大影响。也可以判断一下wget: download timed out后再从代理网址下载。

**Comment by liyanglan** [comment]
判断根本就不准，很多加的判断的国外线路或路由器挂了梯子还是走代理。

**Comment by happymy** [comment]
```
wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppelWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" -T 30 -t 2 http://docker.xiaoya.pro/update/update.zip -O update.zip || \
wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppelWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" --header="Host:docker.xiaoya.pro" -T 30 -t 2 http://104.21.17.247/update/update.zip -O update.zip || \
wget -T 30 -t 2 https://github.com/xiaoyaliu00/data/raw/main/update.zip -O update.zip || \
wget -T 30 -t 2 http://har01d.org/update.zip -O update.zip
```
是这样写的。判断就靠命令是否成功执行。最后一行之前面加上 
`wget -T 30 -t 2 https://xxxx.com/https://github.com/xiaoyaliu00/data/raw/main/update.zip -O update.zip  || \`

关键是找个靠谱的代理网址，有的被拉黑了，有的带有人机检测。

**Comment by power721** [comment]
http://docker.xiaoya.pro/无法访问，导致同步脚本出错。手动修复了。

**Comment by happymy** [comment]
更新初始化脚本 #498
