### ISSUE TITLE
PG 同步与 /www/pg 自定义文件冲突

### ISSUE THREAD

**Issue by tille1229** [power721/alist-tvbox#504]
您必须勾选以下所有内容，否则您的issue可能会被直接关闭。
- [x] 我已经阅读了[文档](https://github.com/power721/alist-tvbox/blob/master/doc/README_zh.md)。
- [x] 我确定没有重复的issue或讨论。
- [x] 我确定是AList-TvBox的问题，而不是其他原因（例如网络，依赖或操作）。
- [x] 我确定这个问题在最新版本中没有被修复。

**描述**
PG更新同步后，会解压缩，覆盖了 `/www/pg` 文件夹下的内容，导致定义在 `/www/pg` 下的文件丢失，需要重新更新自定义文件。

**步骤**
重现问题的步骤:
1. 在 `文件` 菜单中自定义一个文件 `xx.json`，目录 选择 `/www/pg` 或 `/www/pg/lib` ,访问 `http://ip:port/xx.json` 正常 
2. 在 `订阅` 菜单中，点击同步文件
3. 再次访问 `http://ip:port/xx.json`  404 ,进入容器后查看，`/www/pg` 文件夹下文件丢失
4. 真心没测试，可能存在相同的问题
 
**期望的结果**
同步文件能保留文件中自定义的文件

**建议**
* 方式一：同步后，自动重新生成自定义 `/www/pg` 或 `/www/pg/lib` 文件，缺点：可能导致同步时间延长
* 方式二： 新增一个目录及提供访问接口（或直接绑定/www/xx目录），目前存在 `/data` 查看些源码没找到对应的接口地址

**Comment by power721** [comment]
在宿主机/etc/xiaoya/pg/创建文件。

**Comment by tille1229** [comment]
感谢回复，我看见你脚本中会将 `/data/pg` 拷贝到 `/www/pg` 中。这个比较适合不变的场景吧。我使用 `文件`中的自定义配置pg（配置方便）。随着pg版本的更新可能需要调整配置内容。调整的内容在更新后还是会丢失的。这样没办法保持一致了（更新的内容存放在 H2中）。

**Comment by power721** [comment]
修复了

**Comment by tille1229** [comment]
感谢🤗，测试过没问题了。
