### ISSUE TITLE
获取ali open token 串号

### ISSUE THREAD

**Issue by hpkaiq** [power721/alist-tvbox#513]
开放token认证url 使用的这个https://www.voicehub.top/api/v1/oauth/alipan/token
有时候会出现刷新的token不是我的，最夸张的是开了“加载我的云盘”就能看到串号账号网盘里的内容
![image](https://github.com/user-attachments/assets/42c035e7-1253-4418-80fb-cb063c73c79c)
![image](https://github.com/user-attachments/assets/d59dbb84-5296-400c-a98f-757a219dcfba)

**Comment by power721** [comment]
这是第三方服务，我无法控制
