### ISSUE TITLE
开启安全订阅，订阅0中自建的iptv地址无token验证

### ISSUE THREAD

**Issue by z4jst** [power721/alist-tvbox#75]
iptv.m3u是直接放在docker 路径里。开启安全订阅后，订阅0中的 iptv.m3u 地址无随机token，直连即可访问。
即订阅地址是 http://xxx.com:4567/sub/abcde/0
里面的iptv地址是 http://xxx.com:4567/tvbox/iptv.m3u 缺少随机码abcde

**Comment by power721** [comment]
安全订阅是防止阿里账号被滥用。iptv.m3u不需要

**Comment by z4jst** [comment]
好吧 我自用的是私有iptv地址，非公开的。那我想办法换个名字啥的吧。
