### ISSUE TITLE
死于第一步 可能设备垃圾

### ISSUE THREAD

**Issue by DieRose** [power721/alist-tvbox#8]
提示  Error response from daemon: No such container: alist-tvbox 创建容器失败了

**Comment by power721** [comment]
使用命令看看有没有日志：
docker logs xiaoya-tvbox

**Comment by DieRose** [comment]
> 使用命令看看有没有日志： docker logs xiaoya-tvbox
exec /jre/bin/java: exec format error
exec /jre/bin/java: exec format error
exec /jre/bin/java: exec format error
exec /jre/bin/java: exec format error
exec /jre/bin/java: exec format error
exec /jre/bin/java: exec format error

**Comment by power721** [comment]
支持armv8
不支持armv7

**Comment by DieRose** [comment]
> 

设备是v8的

**Comment by power721** [comment]
是用的一键安装脚本？

**Comment by DieRose** [comment]
> 是用的一键安装脚本？

对的

**Comment by power721** [comment]
安装脚本显示的平台是什么？

**Comment by power721** [comment]
修复了，正在发布中

**Comment by DieRose** [comment]
> 修复了，重新安装

感谢
