### ISSUE TITLE
【严重漏洞】token泄漏

### ISSUE THREAD

**Issue by LeeeMooo** [power721/alist-tvbox#81]
帐号页面两个accounts接口没鉴权，直接访问可以获取到阿里和pikpak的token

随便扫了两个
<img width="744" alt="image" src="https://github.com/power721/alist-tvbox/assets/23691333/24a7c201-d6e5-4d29-862c-002ef8132ed5">

<img width="732" alt="image" src="https://github.com/power721/alist-tvbox/assets/23691333/0584786d-cc4e-40c0-8cbd-58a60d736ef5">

**Comment by backtracker** [comment]
测试了一把确实如此

**Comment by power721** [comment]
感谢

**Comment by backtracker** [comment]
这个问题又有了，还是自己用nginx把这2个接口外网访问给毙掉得了

**Comment by power721** [comment]
哪个接口有问题？

**Comment by backtracker** [comment]
> 哪个接口有问题？
/ali/accounts 和 /pikpak/accounts

**Comment by backtracker** [comment]
> 哪个接口有问题？

ali/accounts 和 /pikpak/accounts

**Comment by power721** [comment]
没有问题啊
