### ISSUE TITLE
daocker布置在外网vps，tvbox内丫仙女和哔哩哔哩看不了，布置在软路由就没问题

### ISSUE THREAD

**Issue by ml-cheng** [power721/alist-tvbox#85]
布置后网页可以打开，也有内容，webdave也可用，就是tvbox不能看alist和哔哩哔哩。布置在内网就没问题，望解惑

**Comment by power721** [comment]
看看ngix的反代配置。
是否开启https？

**Comment by ml-cheng** [comment]
谢谢，是设置里误点了https订阅。docker布置的
