### ISSUE TITLE
5244端口未打开

### ISSUE THREAD

**Issue by sevenokey** [power721/alist-tvbox#86]
0d0cd0df9540:/opt/atv# netstat -tuln                                             
Active Internet connections (only servers)                                       
Proto Recv-Q Send-Q Local Address           Foreign Address         State        
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN       
tcp        0      0 0.0.0.0:4567            0.0.0.0:*               LISTEN       
tcp        0      0 127.0.0.1:5244          0.0.0.0:*               LISTEN       
tcp        0      0 :::80                   :::*                    LISTEN       
tcp        0      0 :::81                   :::*                    LISTEN

**Comment by sevenokey** [comment]
根据提供的输出信息，可以看出以下服务器的监听状态：

端口80上的TCP连接正在监听所有可用的IPv4地址（0.0.0.0）。
端口4567上的TCP连接正在监听所有可用的IPv4地址（0.0.0.0）。
端口5244上的TCP连接正在监听本地回环地址127.0.0.1。

**Comment by sevenokey** [comment]
导致本地alist 5244 管理页面进不去

**Comment by power721** [comment]
屏蔽了管理界面，每次重启docker，alist数据库都会被清空。

**Comment by sevenokey** [comment]
如何进入管理页面呢？为什么每次重启docker，alist数据库都会被清空，这样不是很不友好吗

**Comment by power721** [comment]
小雅这样设计的。小雅删除了管理界面的代码
