### ISSUE TITLE
使用tvbox或猫影视，标签里只有最多12个，没有所有目录

### ISSUE THREAD

**Issue by oishi81** [power721/alist-tvbox#89]
在管理面板上看了下，vod/API地址显示：

API返回数据
copy
{
page:1
pagecount:1
limit:12
total:12

![image](https://github.com/power721/alist-tvbox/assets/65519561/283da75b-c6d1-4b28-91f9-cd20690dc804)

而实际目录应有接近20个，那如何才能让所有的目录或者只显示自己想要的目录呢？ 请教大佬们！
![image](https://github.com/power721/alist-tvbox/assets/65519561/60d5a066-90ec-4b54-8cab-c2da88bdc3cb)

**Comment by power721** [comment]
看文档，使用category.txt

**Comment by oishi81** [comment]
> 看文档，使用category.txt

收到回复。
采用category.txt后，实现了只显示自己想要的目录，但有个“我的PikPak分享”一直是没收到数据，这是什么原因呀？ category里设定的名称，需要和小雅主目录下完全一致吗？还是只要包括其中的关键字呀？

![Screenshot_2023-09-28-11-36-14-642_com github tvbox osc tk](https://github.com/power721/alist-tvbox/assets/65519561/27ba8000-75bd-4d61-9598-b89efff9c79f)

**Comment by power721** [comment]
路径需要一致，名称自定义。

**Comment by oishi81** [comment]
已解决。 上面没数据似乎是alist的问题，重新运行了一次，现在没有问题了。
