### ISSUE TITLE
Arm的服务器也不行吗？

### ISSUE THREAD

**Issue by qlql765** [power721/alist-tvbox#9]
日志显示
exec /entrypoint.sh: exec format error

**Comment by power721** [comment]
支持armv8
不支持armv7

**Comment by qlql765** [comment]
> 支持armv8 不支持armv7

还有一个问题就是，如果添加了阿里的分享，那么搜索也会自动索引吗？还是说只能用小雅的搜索数据

**Comment by power721** [comment]
只能用小雅的搜索数据，自动索引可能被阿里封号

**Comment by power721** [comment]
armv8这个问题已经修复
