### ISSUE TITLE
麻烦将bilibili 的显示界面改为16：9模式，参考饭太硬的b站合集源 长方形显示

### ISSUE THREAD

**Issue by kawae0709** [power721/alist-tvbox#99]
麻烦将bilibili 的显示界面改为16：9模式，参考饭太硬的b站合集源 长方形显示

**Comment by power721** [comment]
这个应该是播放器决定的

**Comment by kawae0709** [comment]
我还是自行解决了，blacklist你原装的，后添加我这个type里面有ratio选项的显示挺好的，就是bilibili海报显示是长方形的比较好看！！



{
"ext":"eyJhLZXkiOiJkOWZkMTJhYS1kYzFhLTQ1YjktOWM4Yi00ZTkzZGTdlMzEiLCJhcGkiOiJodHRwOi8vMTAuMTAuMTAuMTg3OjU2NzgifQ==",
"name":"BiliBili",
"key":"csp_BiliBili2",
"type":3,
"style":{
"type":"rect",
"ratio":1.597
},
"jar":"http://10.10.10.187:5678/spring.jar",
"api":"csp_BiliBili",
"changeable":0,
"filterable" : 1,
"quickSearch":1,
"searchable":1
},

**Comment by power721** [comment]
已更新
